### PR TITLE
Bug/ allows OP of embed from transfer to dismiss GPT's response

### LINKED ISSUE #930: dismiss button perms for OP of transfered question
Posts created via transfer-question feature in helper forums should also allow Original author of question to dismiss GPT's answer.

Atm it replies with ephermal message saying,
image

Steps to Reproduce:
1. send text in a text channel
2. open message context menu 
 
image

3. click on transfer-question option inside `Apps`
4. It will create a new post in helper-forum
5. Try to dismiss answer generated by GPT in the newly created post

Note: You shouldn't have any moderation roles

### PR DESCRIPTION
**Pull request by ankitsmt211**
* adds a method to check whether interacting user is author of embed
* refactors if condition to a seperate method for more readability
resolves #930

### CODE REVIEW

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java [hunk 1]
```diff
@@ -159,8 +159,11 @@ public void onButtonClick(ButtonInteractionEvent event, List<String> args) {
         // This method handles chatgpt's automatic response "dismiss" button
         ThreadChannel channel = event.getChannel().asThreadChannel();
         Member interactionUser = Objects.requireNonNull(event.getMember());
-        if (channel.getOwnerIdLong() != interactionUser.getIdLong()
-                && !helper.hasTagManageRole(interactionUser)) {
+        Message forumPostMessage = channel.retrieveMessageById(channel.getId()).complete();
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:162]: use a proper rest action chain, dont do `complete()`.
also, u have to `deferReply`, since the retrieval could take a few seocnds.

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java [hunk 2]
```diff
@@ -182,4 +185,22 @@ public void onModalSubmitted(ModalInteractionEvent event, List<String> args) {
...
+            .getName();
+
+        return embedAuthor.equals(interactionUser.getUser().getName());
+    }
+
+    private boolean isAuthorized(Member interactionUser, ThreadChannel channel,
+            Message forumPostMessage) {
+        return (channel.getOwnerIdLong() == interactionUser.getIdLong())
+                || helper.hasTagManageRole(interactionUser)
+                || (isPostAuthor(interactionUser, forumPostMessage));
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:204]: that (...) around the last statement (isPostAuthor) seems obsolete

**Review by Zabuzard — CHANGES_REQUESTED** [review]

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java (hunk 1 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java]: this one took a while to work out but i think i got it right.

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java [hunk 3]
```diff
@@ -157,16 +158,14 @@ public void acceptComponentIdGenerator(ComponentIdGenerator generator) {
...
-
-        boolean isAuthorized = isAuthorized(interactionUser, channel, forumPostMessage);
 
-        if (!isAuthorized) {
-            event.reply("You do not have permission for this action.").setEphemeral(true).queue();
-            return;
-        }
+        channel.retrieveMessageById(channel.getId())
+            .map(forumPostMessage -> handleAuth(interactionUser, channel, forumPostMessage, event))
+            .queue();
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:168]: that setup doesnt look like it would work. ur still proceeding down to deleting regardless of what this handleAuth thing does.
u likely have to put it into one combined chain of actions.

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java [hunk 4]
```diff
@@ -201,6 +200,16 @@ private boolean isAuthorized(Member interactionUser, ThreadChannel channel,
...
+                || isPostAuthor(interactionUser, forumPostMessage);
+    }
+
+    private RestAction<InteractionHook> handleAuth(Member interactionUser, ThreadChannel channel,
+            Message forumPostMessage, ButtonInteractionEvent event) {
+        boolean isAuthorized = isAuthorized(interactionUser, channel, forumPostMessage);
+        if (!isAuthorized) {
+            event.getInteraction().deferEdit().queue();
+            return event.reply("You do not have permission for this action.").setEphemeral(true);
+        }
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:212]: that doesnt look like it would work, with the `deferEdit` and then `event.reply`. after `defer`, u have to send ur actions via the hook, not the `event` anymore. (the event might also be stale already, considering that `retrieveMessageById` might have taken multiple seconds).
and u can only decide for one, edit or reply. not both

**Review by Zabuzard — CHANGES_REQUESTED** [review]

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java (hunk 3 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:168]: but it does, i have verified it myself. The handleAuth, would basically verify if interacting user is allowed to `dismiss` the message or not, it also replies to user if they are not authorized.

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java (hunk 4 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:212]: I have to acknowledge the defer i believe, `event.getHook()` doesn't seem to have any defer method on it, wym when you say it wouldn't work? i was able to delete the message from gpt using dismiss button.

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java (hunk 3 above)
Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:168]: yeah but the result of that is ignored. it proceeds regardless.

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java (hunk 4 above)
Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:212]: u can either do deferReply or deferEdit. once u did that, u have to do event.getHook() and post ur result via the edit method in that hook.

a regular event.reply(...) is not allowed or safe anymore after u did defer.

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java (hunk 3 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:168]: yep you were right, had to check from alt.

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java (hunk 4 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:206]: added changes, this is what you meant? seems to work, verfied with an alt.

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java [hunk 5]
```diff
@@ -182,4 +178,37 @@ public void onModalSubmitted(ModalInteractionEvent event, List<String> args) {
...
+    private boolean isPostAuthor(Member interactionUser, Message message) {
+        if (message.getEmbeds().isEmpty())
+            return false;
+
+        String embedAuthor = Objects
+            .requireNonNull(message.getEmbeds().get(0).getAuthor(),
+                    "embed author for forum post is null")
+            .getName();
+
+        return embedAuthor.equals(interactionUser.getUser().getName());
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:190]: if possible, compare user ID instead of name

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java [hunk 6]
```diff
@@ -182,4 +178,37 @@ public void onModalSubmitted(ModalInteractionEvent event, List<String> args) {
...
+        return (channel.getOwnerIdLong() == interactionUser.getIdLong())
+                || helper.hasTagManageRole(interactionUser)
+                || isPostAuthor(interactionUser, forumPostMessage);
+    }
+
+    private void handleDismiss(Member interactionUser, ThreadChannel channel,
+            Message forumPostMessage, ButtonInteractionEvent event, List<String> args) {
+        boolean isAuthorized = isAuthorized(interactionUser, channel, forumPostMessage);
+        if (!isAuthorized) {
+            event.getHook().sendMessage("Not allowed").setEphemeral(true).queue();
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:204]: the `Not allowed` reads a bit odd. perhaps `Sorry, you do not have permission to dismiss this message.`

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java (hunk 4 above)
Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:206]: looks better, thanks

**Review by Zabuzard — CHANGES_REQUESTED** [review]

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java (hunk 6 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:204]: Hehe, was meant to be testing only. Will do.

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java (hunk 5 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:190]: seems like only these properties are available for embed authors, shouldnt be a problem tho username is always unique in discord for everyone.
image

Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:190]: alright

**Review by Zabuzard — APPROVED** [review]

**Review by SquidXTV — APPROVED** [review]
