### PR TITLE
handle bot messages transfer action

### LINKED ISSUE #927: Transfer crashes when used on bot-message
The transfer-command should have a fail-safe when triggered on a bot-message.

Right now it crashes because it can not DM bots. Especially when used on itself:

dm bot

### PR DESCRIPTION
**Pull request by ankitsmt211**
resolves #927

Replies with ephermal text to user of feature 
image

### CODE REVIEW

File: application/src/main/java/org/togetherjava/tjbot/features/moderation/TransferQuestionCommand.java [hunk 1]
```diff
@@ -217,4 +222,14 @@ private MessageEmbed makeEmbedForPost(User originalUser, String originalMessage)
 
     private record ForumPost(User author, Message message) {
     }
+
+    private boolean isBotMessageTransfer(MessageContextInteractionEvent event) {
+        if (event.getTarget().getAuthor().isBot()) {
+            event.reply("transfer action is not allowed on messages generated by a Bot")
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/moderation/TransferQuestionCommand.java:228]: For better UX, change text to:

> Cannot transfer messages from a bot.

**Review by Zabuzard — CHANGES_REQUESTED** [review]

**Comment by ankitsmt211** [comment]
Accidentally pushed a different branch, that explains the need for last commit 👀

**Review by Zabuzard — APPROVED** [review]

**Review by Taz03 — APPROVED** [review]
