### PR TITLE
Fixed bug with MediaOnlyChannelListener when user closed DMs

### LINKED ISSUE #748: MediaOnlyChannelListener DM failure shouldnt result in an error
The `MediaOnlyChannelListener` sends DMs to the authors of a message to inform them about the action. Thats totally fine and expected, but failure to DM a user (for example if they blocked DMs), it should not yield to an exception being thrown in the logs:

> ```java
> RestAction queue returned failure: [ErrorResponseException] 50007: Cannot send messages to this user
> net.dv8tion.jda.api.exceptions.ContextException
> at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
> at net.dv8tion.jda.internal.requests.restaction.operator.RestActionOperator.contextWrap(RestActionOperator.java:123)
> at net.dv8tion.jda.internal.requests.restaction.operator.FlatMapRestAction.queue(FlatMapRestAction.java:50)
> at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:572)
> at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:538)
> at org.togetherjava.tjbot.commands.mediaonly.MediaOnlyChannelListener.onMessageReceived(MediaOnlyChannelListener.java:48)
> at org.togetherjava.tjbot.commands.system.BotCore.lambda$onMessageReceived$9(BotCore.java:205)
> at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
> at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java...
> ```

The actual DM sending should probably use `mapToResults()` and then maybe send a DEBUG level log message:

code

Even better would be to send a message in the channel that pings the user instead and then delete that message after a minute again. But its also okay to go without that for now.

### PR DESCRIPTION
**Pull request by AthithyaIthayan**
Fixes and closes #748 by sending a temporary message in the channel if DMs fail (the message is deleted after 1min)

### CODE REVIEW

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java [hunk 1]
```diff
@@ -45,7 +48,12 @@ public void onMessageReceived(MessageReceivedEvent event) {
         }
 
         if (messageHasNoMediaAttached(message)) {
-            message.delete().flatMap(any -> dmUser(message)).queue();
+            message.delete().flatMap(any -> dmUser(message)).queue(res -> {
```
Comment (Taz03) [inline application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:51]:
```suggestion
            message.delete().flatMap(any -> dmUser(message)).queue(any -> {
```
any basically tells that ur not gonna use it

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java [hunk 2]
```diff
@@ -45,7 +48,12 @@ public void onMessageReceived(MessageReceivedEvent event) {
...
+            }, new ErrorHandler().handle(ErrorResponse.CANNOT_SEND_TO_USER, err -> {
```
Comment (Taz03) [inline application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:52]: u dont have to specify all those stuff just do 
```java
queue(any -> {}, err -> { ... })
```

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java [hunk 3]
```diff
@@ -45,7 +48,12 @@ public void onMessageReceived(MessageReceivedEvent event) {
...
+                warnUser(message).queue((res) -> {
+                    res.delete().queueAfter(1, TimeUnit.MINUTES);
+                });
```
Comment (Taz03) [inline application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:55]:
```suggestion
                warnUser(message).queue(res -> res.delete().queueAfter(1, TimeUnit.MINUTES));
```
name it something better as well

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java [hunk 4]
```diff
@@ -54,20 +62,37 @@ private boolean messageHasNoMediaAttached(Message message) {
...
-            .build();
+                        "Hey there, you posted a message without media (image, video, link) in a media-only channel. Please see the description of the channel for details and then repost with media attached, thanks 😀")
+                .setEmbeds(originalMessageEmbed)
+                .build();
 
         return message.getAuthor()
-            .openPrivateChannel()
-            .flatMap(channel -> channel.sendMessage(dmMessage));
+                .openPrivateChannel()
+                .flatMap(channel -> channel.sendMessage(dmMessage));
```
Comment (Taz03) [inline application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:96]: instead have method which gives u MessageCreateBuilder(will the all data, i.e. message and embeds set already) of the common part then send it where u need to for example
```java
message.delete()
    .flatMap(any -> message.getAuthor()
        .openPrivateChannel()
        .flatMap(channel -> channel.sendMessage(getWarnMessage(message).build())))
    .queue( ... );
```

**Review by Taz03 — CHANGES_REQUESTED** [review]

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java (hunk 1 above)
Comment (AthithyaIthayan) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:51]: got it done

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java (hunk 2 above)
Comment (AthithyaIthayan) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:52]: done updated

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java (hunk 3 above)
Comment (AthithyaIthayan) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:55]: Done

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java (hunk 4 above)
Comment (AthithyaIthayan) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:96]: Its Exactly the same thing just out of the Function creating 2 more functions. 
does it improve its Efficiency?

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java [hunk 5]
```diff
@@ -45,7 +46,11 @@ public void onMessageReceived(MessageReceivedEvent event) {
         }
 
         if (messageHasNoMediaAttached(message)) {
-            message.delete().flatMap(any -> dmUser(message)).queue();
+            message.delete().flatMap(any -> dmUser(message)).queue(any -> {
+            }, err -> {
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:50]: dont abbreviate, `err` is a bad name. that said, we usually use `failure` here.

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java [hunk 6]
```diff
@@ -45,7 +46,11 @@ public void onMessageReceived(MessageReceivedEvent event) {
...
+                pingUserAobutMedia(message)
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:51]: * typo. `About`, not `Aobut`
* also kinda a bad name, "about media" - what about? what happened? and its also too specific with the "ping" - can quickly get out of date if someone changes its internals
* better would be to go with the current pattern in this class, where it says `dmUser` and now u can instead use `pingUserInChannel`. also makes clear why its the alternative

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java [hunk 7]
```diff
@@ -45,7 +46,11 @@ public void onMessageReceived(MessageReceivedEvent event) {
...
+                    .queue(res -> res.delete().queueAfter(1, TimeUnit.MINUTES));
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:52]: what is `res`? bad name

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java [hunk 8]
```diff
@@ -54,12 +59,29 @@ private boolean messageHasNoMediaAttached(Message message) {
                 && !message.getContentRaw().contains("http");
     }
 
-    private RestAction<Message> dmUser(Message message) {
+    private MessageEmbed originalMessageEmbed(Message message) {
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:62]: weird method name. i also dont quite get why it exists in the first place

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java [hunk 9]
```diff
@@ -54,12 +59,29 @@ private boolean messageHasNoMediaAttached(Message message) {
...
+    private RestAction<Message> pingUserAobutMedia(Message message) {
+        MessageEmbed originalMessageEmbed = originalMessageEmbed(message);
+
+        long authorId = message.getAuthor().getIdLong();
+
+        MessageCreateData pingMessage = new MessageCreateBuilder().setContent("Hey there, you <@"
+                + authorId
+                + "> posted a message without media (image, video, link) in a media-only channel. Please see the description of the channel for details and then repost with media attached, thanks 😀")
+            .setEmbeds(originalMessageEmbed)
+            .build();
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:78]: * dont mention manually, instead use JDAs methods, like `author.getAsMention()`.
* lots of code duplication with the `dmUser` method. instead, let both methods use the same text and just add the ping as prefix or similar here.

**Review by Zabuzard — CHANGES_REQUESTED** [review]

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java (hunk 7 above)
Comment (AthithyaIthayan) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:52]: Shall I make it result or success ?

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java (hunk 8 above)
Comment (AthithyaIthayan) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:62]: This existed previously so I didn't Intend to change it  like do I remove it or rename it now?

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java (hunk 9 above)
Comment (AthithyaIthayan) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:78]: What is the duplicate I expected both to have different message in future so I did make them different

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java (hunk 7 above)
Comment (Taz03) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:52]: none, id say `warningMessage`

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java (hunk 8 above)
Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:62]: it did not exist as a seperate method originally. previously it was a variable name and in that context the name made sense. but not as seperate method like that.

Comment (Taz03) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:62]: this didn't existed previously, there was no method which returned the message embed and only that

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java (hunk 7 above)
Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:52]: ah it stands for result. i thought its resource - see, thats why abbreviating is **bad**.
call it what it is, namely the `notificationMessage` or similar

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java (hunk 9 above)
Comment (Taz03) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:78]: they are the same just with a ping in between(which can go anywhere)

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java (hunk 8 above)
Comment (AthithyaIthayan) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:62]: Original dmUser had a embed it was common to ping and dm so I made a function out of it

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java (hunk 9 above)
Comment (AthithyaIthayan) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:78]: ok I will change it

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java (hunk 8 above)
Comment (AthithyaIthayan) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:62]: Yes ok le me move it also

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java (hunk 4 above)
Comment (AthithyaIthayan) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java]: Ok I will update it

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java (hunk 5 above)
Comment (AthithyaIthayan) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:50]: I will update in the next push

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java (hunk 7 above)
Comment (AthithyaIthayan) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:52]: I update it with `notificationMessage `

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java (hunk 6 above)
Comment (AthithyaIthayan) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java]: I renamed and uniied the function can u just go through them the newer set?

**Comment by AthithyaIthayan** [comment]
https://user-images.githubusercontent.com/118907229/218473911-d91a48fc-9cac-4130-bcdc-e1af14e48538.mp4

**Comment by Taz03** [comment]
@AthithyaIthayan great, there are a few lint issues tho, u'll need to fix those

**Review by Taz03 — APPROVED** [review]

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java [hunk 10]
```diff
@@ -45,7 +45,15 @@ public void onMessageReceived(MessageReceivedEvent event) {
...
-            message.delete().flatMap(any -> dmUser(message)).queue();
+            message.delete()
+                .flatMap(any -> message.getAuthor()
+                    .openPrivateChannel()
+                    .flatMap(channel -> channel.sendMessage(warningMessage(message))))
+                .queue(any -> {
+                }, failure -> message.getChannel()
+                    .sendMessage(warningMessage(message))
+                    .queue(notificationMessage -> notificationMessage.delete()
+                        .queueAfter(1, TimeUnit.MINUTES)));
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:56]: this is really long and complex now. not sure why u removed `dmUser`. please change this code by using utility methods so that in the end its just:
```java
message.delete()
  .flatMap(any -> dmUser(message))
  .queue(any -> {}, failure -> tempNotifyUserInChannel(message));
```

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java [hunk 11]
```diff
@@ -54,20 +62,18 @@ private boolean messageHasNoMediaAttached(Message message) {
                 && !message.getContentRaw().contains("http");
     }
 
-    private RestAction<Message> dmUser(Message message) {
+    private MessageCreateData warningMessage(Message message) {
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:65]: its more a notification than a warning. also, since its a method, the name should have a verb, such as `create...`.

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java [hunk 12]
```diff
@@ -54,20 +62,18 @@ private boolean messageHasNoMediaAttached(Message message) {
...
         MessageEmbed originalMessageEmbed =
                 new EmbedBuilder().setDescription(originalMessageContent)
                     .setColor(Color.ORANGE)
                     .build();
 
-        MessageCreateData dmMessage = new MessageCreateBuilder().setContent(
-                "Hey there, you posted a message without media (image, video, link) in a media-only channel. Please see the description of the channel for details and then repost with media attached, thanks 😀")
+        return new MessageCreateBuilder().setContent("Hey there, you "
+                + message.getAuthor().getAsMention()
+                + " posted a message without media (image, video, link) in a media-only channel. Please see the description of the channel for details and then repost with media attached, thanks 😀")
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:75]: reads weird with the mention right in the text. put it at the very front instead. `"@Foo Hey there, you posted a ..."`

**Review by Zabuzard — CHANGES_REQUESTED** [review]

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java (hunk 12 above)
Comment (AthithyaIthayan) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:75]: Ok I will update the Text

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java (hunk 11 above)
Comment (AthithyaIthayan) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:65]: ok I will do it

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java (hunk 10 above)
Comment (AthithyaIthayan) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:56]: https://github.com/Together-Java/TJ-Bot/pull/769#discussion_r1103854200

I was asked it to modify it the other way

Comment (Taz03) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java]: @Zabuzard whats the problem with current method? a single method to get the message and send it where wanted

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java (hunk 12 above)
Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java]: u forgot the space

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java (hunk 10 above)
Comment (AthithyaIthayan) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java]: @Taz03 
Is this a better approach ??
(or )
shall I make 3 functions 
1. message Building
2. Dm user
3. Temporary message?

Comment (Taz03) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java]: isn't that what zabu said as well? im ok with it

Comment (AthithyaIthayan) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java]: which one 3 functions @Taz03

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java (hunk 12 above)
Comment (AthithyaIthayan) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java]: done I updated it

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java (hunk 10 above)
Comment (AthithyaIthayan) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java]: I did resolve it this time check it out

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java [hunk 13]
```diff
@@ -45,15 +46,10 @@ public void onMessageReceived(MessageReceivedEvent event) {
...
-                    .flatMap(channel -> channel.sendMessage(createNotificationMessage(message))))
-                .queue(any -> {
-                }, failure -> message.getChannel()
-                    .sendMessage(createNotificationMessage(message))
-                    .queue(notificationMessage -> notificationMessage.delete()
-                        .queueAfter(1, TimeUnit.MINUTES)));
+            message.delete().flatMap(any -> dmUser(message)).queue(any -> {
+            }, failure -> tempNotifyUserInChannel(message)
+                .queue(notificationMessage -> notificationMessage.delete()
+                    .queueAfter(1, TimeUnit.MINUTES)));
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:52]: please move the details of the temp thing into the method as well. it should look like
```java
message.delete()
  .flatMap(any -> dmUser(message))
  .queue(any -> {}, failure -> tempNotifyUserInChannel(message));
```

**Review by Zabuzard — CHANGES_REQUESTED** [review]

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java (hunk 13 above)
Comment (AthithyaIthayan) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java]: Just watch the bot now is it ok?
I did update it

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java [hunk 14]
```diff
@@ -13,6 +13,7 @@
 import org.togetherjava.tjbot.features.MessageReceiverAdapter;
 
 import java.awt.Color;
+import java.util.concurrent.ScheduledFuture;
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:16]: where is that import coming from? looks unecessary

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java [hunk 15]
```diff
@@ -48,8 +49,7 @@ public void onMessageReceived(MessageReceivedEvent event) {
         if (messageHasNoMediaAttached(message)) {
             message.delete().flatMap(any -> dmUser(message)).queue(any -> {
             }, failure -> tempNotifyUserInChannel(message)
-                .queue(notificationMessage -> notificationMessage.delete()
-                    .queueAfter(1, TimeUnit.MINUTES)));
+            );
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:52]: sure that passes spotless? looks to me like u commited without running the pre-commit hooks.

**Review by Zabuzard — CHANGES_REQUESTED** [review]

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java (hunk 15 above)
Comment (Taz03) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:52]: even if it does move it up

Comment (AthithyaIthayan) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:52]: I forgot spotless I will do it a sec

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java (hunk 14 above)
Comment (AthithyaIthayan) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java:16]: Its Extra I will remove it

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java (hunk 13 above)
Comment (AthithyaIthayan) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java]: I this fixed?

File: application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java (hunk 15 above)
Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/mediaonly/MediaOnlyChannelListener.java]: if u have set up ur IDE correctly, u cant forget it. it would auto-execute during commit. its called a pre-commit hook 😄  thanks though

**Review by Zabuzard — APPROVED** [review]
good stuff 👍

**Review by Taz03 — APPROVED** [review]
