### PR TITLE
Handling /reminder failure cases 

### LINKED ISSUE #722: /remind should retry and log after failure
## Problem

Our reminder system (`/reminder create ...`) sometimes fails to send the reminder. This is totally normal and can happen due to Discord/JDA hicups and whatever.

But, when it happens, we completely lose the message and it does not retry. That is a problem.

## Fix

Instead, the system should just retry failed reminders (maybe 3 times), by putting them into the DB again with an `Instant` that is maybe set 1 minute into the future. If it ultimately failed, the log message should log the actual reminder-text and the target user, so that the reminder can be rerouted manually by an admin at least.

## Details

For the failure count (~3 times), we likely need to add an additional column in the reminder DB table. Reminders are send from `RemindRoutine.java`, the table was initially created in `V8__Add_Pending_Reminders.sql`, the migration script `V10__Alter_Top_Helper_Message_Length.sql` shows how one can add a new column to an existing table.

### PR DESCRIPTION
**Pull request by ankitsmt211**
Added a file to alter `PENDING_REMINDER_TABLE` to add another column `REMINDER_FAILURE_COUNTER` which keeps track of attempts made when `/reminder` fails. 

Also modified `RemindRoutine` class to handle failures

Closes and fixes #722

### CODE REVIEW

**Comment by ankitsmt211** [comment]
what's happening, is it something wrong with code? not familiar with these automated checks

**Comment by Taz03** [comment]
> what's happening, is it something wrong with code? not familiar with these automated checks

u can click on details to know what each are about

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java [hunk 1]
```diff
@@ -1,5 +1,6 @@
 package org.togetherjava.tjbot.features.reminder;
 
+import com.sun.source.tree.OpensTree;
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:3]: whats that import? looks odd

File: application/src/main/resources/db/V13__Add_Reminder_Failure_Counter.sql [hunk 2]
```diff
@@ -0,0 +1 @@
+ALTER TABLE pending_reminders ADD reminder_failure_counter INTEGER DEFAULT 0;
```
Comment (Zabuzard) [inline application/src/main/resources/db/V13__Add_Reminder_Failure_Counter.sql:1]: * its clear from the context that its a reminder-thing, so id rename it to just `failure_counter`. or, to make it clearer what it actually is, `failed_attempts`
* its missing a `NOT NULL` at the end

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java [hunk 3]
```diff
@@ -55,25 +58,27 @@ public Schedule createSchedule() {
...
+                            pendingReminder.getAuthorId(), pendingReminder.getContent(),
+                            pendingReminder.getCreatedAt(), pendingReminder.getGuildId());
+
+                    pendingReminder.delete();
+                }));
     }
 
-    private static void sendReminder(JDA jda, long id, long channelId, long authorId,
-            CharSequence content, TemporalAccessor createdAt) {
+    private void sendReminder(JDA jda, int id, long channelId, long authorId,
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:72]: why did u change the id to `int`? isnt it a `long`? what does `pendingReminder.getId()` return?

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java [hunk 4]
```diff
@@ -142,4 +146,35 @@ static ReminderRoute toPrivate(PrivateChannel channel) {
...
+                            user has disabled DMs or has been deleted."""+ "contents: "+content,
+                    authorId);
+        }
+    }
+
+        private Integer getReminderFailureCounter(int id){
+            return database.read(context -> context.selectFrom(PENDING_REMINDERS).where(PENDING_REMINDERS.ID.eq(id))
+                    .stream().map(PendingRemindersRecord::getReminderFailureCounter).findFirst().get()
+            );
+        }
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:178]: it is unecessary that u read the database again. u can get hands on the failure counter where u read it originally, here:

original

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java [hunk 5]
```diff
@@ -85,43 +90,42 @@ private static RestAction<ReminderRoute> computeReminderRoute(JDA jda, long chan
...
-        Consumer<Throwable> logFailure = failure -> logger.warn(
-                """
-                        Failed to send a reminder (id '{}'), skipping it. This can be due to a network issue, \
-                        but also happen if the bot disconnected from the target guild and the \
-                        user has disabled DMs or has been deleted.""",
-                id);
+        Consumer<Throwable> logFailure = failure -> {
+            //
+            reminderFailureAction(id, channelId, authorId, content, guildId, reminderFailureCount);
+        };
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:113]: the name `logFailure` is kinda incorrect now. that said, i would just put the lambda without defining it in advance now. so `.queue(doNothing(), failure -> reminderFailureAction(...))`

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java [hunk 6]
```diff
@@ -142,4 +146,35 @@ static ReminderRoute toPrivate(PrivateChannel channel) {
                             + " the original channel you wanted it to be send to)");
         }
     }
-}
+
+    private void reminderFailureAction(int id, long channelId, long authorId,
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:150]: the name is kinda bad. what about `attemptRetryReminder`

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java [hunk 7]
```diff
@@ -142,4 +146,35 @@ static ReminderRoute toPrivate(PrivateChannel channel) {
...
+                                       CharSequence content, long guildId, int reminderFailureCounter) {
+        if (reminderFailureCounter <= 3) {
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:152]: 3 is a magic number. put it into a well named constant `MAX_RETRY_ATTEMPTS` instead

Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:152]: prefer to not do:
```java
if (...) {
  some long code
} else {
  sth short
}
```
instead, use early-return:
```java
if (!...) {
  sth short
  return
}

sth long
```
that way, u have no nesting for the long part and its more readable

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java [hunk 8]
```diff
@@ -142,4 +146,35 @@ static ReminderRoute toPrivate(PrivateChannel channel) {
...
+            Instant current = Instant.now();
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:153]: instead of putting current here and computing the remindAt at the bottom, compute it up here. `Instant remindAt = Instant.now().plusMinutes(1)`

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java [hunk 9]
```diff
@@ -142,4 +146,35 @@ static ReminderRoute toPrivate(PrivateChannel channel) {
...
+            database.write(context -> context.newRecord(PENDING_REMINDERS)
+                    .setId(id)
+                    .setCreatedAt(Instant.now())
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:156]: please use the original "createdAt", not a new one

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java [hunk 10]
```diff
@@ -142,4 +146,35 @@ static ReminderRoute toPrivate(PrivateChannel channel) {
...
+                    .setContent(content.toString())
+                    .setReminderFailureCounter(reminderFailureCounter + 1)
+                    .insert());
+        } else {
+            logger.warn(
+                    """
+                            Failed to send a reminder with (authorID '{}'), skipping it. This can be due to a network issue, \
+                            but also happen if the bot disconnected from the target guild and the \
+                            user has disabled DMs or has been deleted."""+ "contents: "+content,
+                    authorId);
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:170]: dont do string concatenation on a logger. instead use its string interpolation mechanism with `{}`.

```java
logger.warn("Failed to send a reminder after {} retry attempts (id '{}', from author '{}'), skipping it. ... The content was: {}",
  id, authorId, MAX_RETRY_ATTEMPTS, content)
```

**Review by Zabuzard — CHANGES_REQUESTED** [review]

**Comment by Zabuzard** [comment]
@ankitsmt211 the issues are mostly related to your code style. u seem to have bypassed the pre-commit hook when u commited and by that skipped **spotless**. either setup ur pre-commit hooks or run `gradle spotless:apply`

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 1 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:3]: It wasn't supposed to be there, since the imports were minimized it slipped through. Fixed it after installing sonarLint plugin.

File: application/src/main/resources/db/V13__Add_Reminder_Failure_Counter.sql (hunk 2 above)
Comment (ankitsmt211) [reply application/src/main/resources/db/V13__Add_Reminder_Failure_Counter.sql:1]: done

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 5 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:113]: resolved this as well

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 7 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:152]: i had a feeling that was incorrect way of doing it, makes it hard to look for it and change in future.

Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:152]: done

Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:152]: its usually easier for people to adjust constants when they are in the expected place (at the beginning of the file) and not in the middle of the code flow

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 3 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:72]: image
The table's ID field was Integer, so i think that's why i changed it.

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java [hunk 11]
```diff
@@ -85,43 +90,42 @@ private static RestAction<ReminderRoute> computeReminderRoute(JDA jda, long chan
...
+                .setContent(route.description());
 
-        Consumer<Throwable> logFailure = failure -> logger.warn(
-                """
-                        Failed to send a reminder (id '{}'), skipping it. This can be due to a network issue, \
-                        but also happen if the bot disconnected from the target guild and the \
-                        user has disabled DMs or has been deleted.""",
-                id);
+        Consumer<Throwable> logFailure = failure -> {
+            //
```
[the remark this answers is not in the document]
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:111]: fixed it

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 4 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:178]: fixed it

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 6 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:150]: just saw this and updated to `attemptRetryReminder`

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 3 above)
Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java]: ah. please note that sqlites `INTEGER` type is also for `long`. its a variable size integer :)

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java [hunk 12]
```diff
@@ -147,34 +134,29 @@ static ReminderRoute toPrivate(PrivateChannel channel) {
...
-                    .setGuildId(guildId)
-                    .setChannelId(channelId)
-                    .setAuthorId(authorId)
-                    .setRemindAt(current.plusSeconds(60))
-                    .setContent(content.toString())
-                    .setReminderFailureCounter(reminderFailureCounter + 1)
-                    .insert());
-        } else {
+    private void attemptRetryReminder(Reminder reminder) {
+        if (!(reminder.failureAttempts() <= MAX_FAILURE_RETRY)) {
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:138]: kinda complex to read. instead do `foo > bar`

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java [hunk 13]
```diff
@@ -147,34 +134,29 @@ static ReminderRoute toPrivate(PrivateChannel channel) {
...
+                    reminder.authorId(),reminder.content());
+            return;
 
-        private Integer getReminderFailureCounter(int id){
-            return database.read(context -> context.selectFrom(PENDING_REMINDERS).where(PENDING_REMINDERS.ID.eq(id))
-                    .stream().map(PendingRemindersRecord::getReminderFailureCounter).findFirst().get()
-            );
         }
+
+        Instant current = Instant.now().plusSeconds(60);
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:149]: the naming is now incorrect. go for `remindAt`

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java [hunk 14]
```diff
@@ -147,34 +134,29 @@ static ReminderRoute toPrivate(PrivateChannel channel) {
...
-                    .setContent(content.toString())
-                    .setReminderFailureCounter(reminderFailureCounter + 1)
-                    .insert());
-        } else {
+    private void attemptRetryReminder(Reminder reminder) {
+        if (!(reminder.failureAttempts() <= MAX_FAILURE_RETRY)) {
             logger.warn(
                     """
-                            Failed to send a reminder with (authorID '{}'), skipping it. This can be due to a network issue, \
+                            Failed to send a reminder with (authorID '{}') and (content '{}'), skipping it. This can be due to a network issue, \
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:141]: personally, id put the content at the very end of the log message. the content can be really long text and its hard to read the log message if its put right into the sentence

Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:141]: also, it would be helpful to have the reminder ID, not just the author ID

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java [hunk 15]
```diff
@@ -11,17 +10,13 @@
...
 import org.slf4j.LoggerFactory;
-
 import org.togetherjava.tjbot.db.Database;
-import org.togetherjava.tjbot.db.generated.tables.records.PendingRemindersRecord;
 import org.togetherjava.tjbot.features.Routine;
 
 import javax.annotation.Nullable;
-
-import java.awt.Color;
+import java.awt.*;
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:17]: star-import on `java.awt` is "forbidden", since it quickly leads to bugs with `java.awt.List` vs `java.util.List`. please configure ur IDE import-settings to disallow star import on java.awt, thanks

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java [hunk 16]
```diff
@@ -61,20 +57,18 @@ public void runRoutine(JDA jda) {
                 .where(PENDING_REMINDERS.REMIND_AT.lessOrEqual(now))
                 .stream()
                 .forEach(pendingReminder -> {
-                    sendReminder(jda, pendingReminder.getId(), pendingReminder.getChannelId(),
-                            pendingReminder.getAuthorId(), pendingReminder.getContent(),
-                            pendingReminder.getCreatedAt(), pendingReminder.getGuildId());
+                    Reminder reminder = new Reminder(pendingReminder.getId(),pendingReminder.getCreatedAt(),
+                            pendingReminder.getGuildId(),pendingReminder.getChannelId(),pendingReminder.getAuthorId(),
+                            pendingReminder.getRemindAt(),pendingReminder.getContent(),pendingReminder.getFailureAttempts());
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:62]: u can improve the code if u give ur `Reminder` record a method:
```java
public static Reminder from(PendingReminder pendingReminder) {
  return new Reminder(...);
}
```
then u can write `sendReminder(jda, Reminder.from(pendingReminder));` here

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java [hunk 17]
```diff
@@ -147,34 +134,29 @@ static ReminderRoute toPrivate(PrivateChannel channel) {
...
                     """
-                            Failed to send a reminder with (authorID '{}'), skipping it. This can be due to a network issue, \
+                            Failed to send a reminder with (authorID '{}') and (content '{}'), skipping it. This can be due to a network issue, \
                             but also happen if the bot disconnected from the target guild and the \
-                            user has disabled DMs or has been deleted."""+ "contents: "+content,
-                    authorId);
-        }
-    }
+                            user has disabled DMs or has been deleted.""",
+                    reminder.authorId(),reminder.content());
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:144]: imo the log should also log the failure exception. otherwise we cant investigate why it failed

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java [hunk 18]
```diff
@@ -147,34 +134,29 @@ static ReminderRoute toPrivate(PrivateChannel channel) {
...
+        Instant current = Instant.now().plusSeconds(60);
+        database.write(context -> context.newRecord(PENDING_REMINDERS)
+                .setId(reminder.id())
+                        .setCreatedAt(reminder.createdAt())
+                .setGuildId(reminder.guildId())
+                .setChannelId(reminder.channelId())
+                .setAuthorId(reminder.authorId())
+                .setRemindAt(current)
+                .setContent(reminder.content())
+                .setReminderFailureCounter(reminder.failureAttempts()+1)
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:158]: to make it visually standing out better, id put this crucial line into a seperate variable beforehand:
```java
int failureAttempts = reminder.failureAttempts() + 1;

...

  .setReminderFailureCounter(failureAttempts)
```

**Review by Zabuzard — CHANGES_REQUESTED** [review]

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 12 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:138]: yep just fixed this one, idk why i went with that without thinking why you suggested what you suggested earlier. Over complicated it for no reasons.

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 13 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:149]: fixed this

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 14 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:141]: yea kinda makes sense, didn't think like that because never really used logging.

Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:141]: fixed this

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 15 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:17]: fixed it for this one, not sure how to change import settings but ill look into it

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 16 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:62]: can i actually do that? couldn't find anything related to from keyword in `records`

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 17 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:144]: do i need to create a custom exception?

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 3 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java]: so im not sure whether to keep it as `int` type or switch back to `long`?

Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java]: `long` please :)

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 15 above)
Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:17]: `intellij settings > code style > imports > dont use * for ...` sth like that

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 16 above)
Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:62]: records are just classes, u can give them methods:
```java
record Person(String name, int age) {
  public static Person from(String line) {
    ...
  }
}
```

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 17 above)
Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:144]: no. just carry the `failure` through the method param and then attach it to the log as last parameter `logger.warn(..., failure)`. the logger will auto-attach the stacktrace if u put it as last argument

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 16 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:62]: image
 is this really better? kinda makes `getters` longer than how it used to be
for ex: earlier i could access any field using `reminder.field`, but now it has to be `reminder.pendingReminders().field()`

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 17 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:144]: i should prolly use `failure.getMessage()`? to get proper message from failure throwable

**Comment by ankitsmt211** [comment]
Please don't run the checks yet, this still needs some work and i had to update the recent changes to my remote repo atm.

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java [hunk 19]
```diff
@@ -58,18 +59,17 @@ public void runRoutine(JDA jda) {
             .where(PENDING_REMINDERS.REMIND_AT.lessOrEqual(now))
             .stream()
             .forEach(pendingReminder -> {
-                sendReminder(jda, pendingReminder.getId(), pendingReminder.getChannelId(),
-                        pendingReminder.getAuthorId(), pendingReminder.getContent(),
-                        pendingReminder.getCreatedAt());
+                sendReminder(jda, Reminder.from(pendingReminder));
```
Comment (Taz03) [inline application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:62]: pass the pendingReminder all along

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java [hunk 20]
```diff
@@ -142,4 +136,32 @@ static ReminderRoute toPrivate(PrivateChannel channel) {
...
+        database.write(context -> context.newRecord(PENDING_REMINDERS)
+            .setId(reminder.pendingReminders().getId())
+            .setCreatedAt(Instant.from(reminder.pendingReminders().getCreatedAt()))
+            .setGuildId(reminder.pendingReminders().getGuildId())
+            .setChannelId(reminder.pendingReminders().getChannelId())
+            .setAuthorId(reminder.pendingReminders().getAuthorId())
+            .setRemindAt(remindAt)
+            .setContent(reminder.pendingReminders().getContent())
+            .setFailureAttempts(failureAttempts)
+            .insert());
```
Comment (Taz03) [inline application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:165]: y u need to add it to the db?? just attempt 3 times in ur code

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/Reminder.java [hunk 21]
```diff
@@ -0,0 +1,12 @@
+package org.togetherjava.tjbot.features.reminder;
+
+import org.togetherjava.tjbot.db.generated.tables.records.PendingRemindersRecord;
+
+public record Reminder(PendingRemindersRecord pendingReminders) {
+
+    public static Reminder from(PendingRemindersRecord pendingReminders) {
+        return new Reminder(pendingReminders);
+    }
```
Comment (Taz03) [inline application/src/main/java/org/togetherjava/tjbot/features/reminder/Reminder.java:9]: makes no sense to have a `from` method, just do `new Reminder(pendingReminder)` y the name is plural btw?

File: application/src/main/resources/db/V13__Add_Reminder_Failure_attempts.sql [hunk 22]
```diff
@@ -0,0 +1 @@
+ALTER TABLE pending_reminders ADD failure_attempts INTEGER DEFAULT 0 NOT NULL ;
```
Comment (Taz03) [inline application/src/main/resources/db/V13__Add_Reminder_Failure_attempts.sql:1]: i believe not null should be before default

**Review by Taz03 — CHANGES_REQUESTED** [review]

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 20 above)
Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:165]: @Taz03 we decided on that early on. its the easiest approach and also works if the bot might shutdown or crash in between.

if u retry in-code, u have to add the delay (+1 minute) manually and create a proper retry-loop. thats not trivial at all. its much easier to just let the system pick the reminder up again naturally by simply reinserting 🤷

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 19 above)
Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:62]: gonna double check if thats possible. the `pendingReminder` itself might still be tied to the DB and hold the resource open.

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 20 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:165]: that's what issue suggested, adding a separate column to keep track of `failure_attempts`

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/Reminder.java (hunk 21 above)
Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/Reminder.java:9]: then u need to create a second constructor that chains to the original per-value constructor? also possible

File: application/src/main/resources/db/V13__Add_Reminder_Failure_attempts.sql (hunk 22 above)
Comment (Zabuzard) [reply application/src/main/resources/db/V13__Add_Reminder_Failure_attempts.sql:1]: checking other examples in our code base, it doesnt seem to matter. the only odd thing is the space before the semicolon `;`

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 19 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:62]: if that's not possible i was thinking instead of using `from` method inside record i think it's better to just use `record` otherwise it ends up with really longer calls like `reminder.pendingReminder().getId()`, earlier it was something like `reminder.Id()` with just records.

Comment (Taz03) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:62]: i can't see a reason y it is not possible, do u get an error or something? I believe i've that in this repo somewhere

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 3 above)
Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java]: ah. okay. if the autogenerated code has `int`, then im okay with having `int`.

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java [hunk 23]
```diff
@@ -142,4 +136,32 @@ static ReminderRoute toPrivate(PrivateChannel channel) {
...
         }
     }
+
+    private void attemptRetryReminder(Reminder reminder, Throwable failure) {
+        if (reminder.pendingReminders().getFailureAttempts() > MAX_FAILURE_RETRY) {
+            logger
+                .warn("""
+                        Failed to send a reminder with (authorID '{}') skipping it. This can be due to a network issue, \
+                        but also happen if the bot disconnected from the target guild and the \
+                        user has disabled DMs or has been deleted. It's (content includes '{}' with reminderId '{}'). The reason for (failure '{}')""",
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:146]: The content-sentence looks and reads weird:

> It's (content includes 'hello world please remind me about foo bar blablabla haha' with reminderId '13').

Instead, go for:

> Reminder id 13, content is: hello world please remind me about foo bar blablabla haha

Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:146]: having the `failure` in the message itself is incorrect. the logger will auto-attach it, dont add it to the string. just drop the last sentence, but keep it as last parameter in the method call

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 16 above)
Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java]: no. u misunderstood me here. i meant like:

```java
record Reminder(String name, int age) {
  public static Reminder from(PendingReminder other) {
    return new Reminder(other.getName(), other.getAge())
  }
}
```
the `Reminder` was not supposed to wrap the `PendingReminder`, but to extract all its content into its own fields.

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 17 above)
Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java]: (u did it wrong, see comment in newest CR)

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java [hunk 24]
```diff
@@ -142,4 +136,32 @@ static ReminderRoute toPrivate(PrivateChannel channel) {
...
+                        reminder.pendingReminders().getAuthorId(),
+                        reminder.pendingReminders().getContent(),
+                        reminder.pendingReminders().getId(), failure);
+            return;
+
+        }
+
+        int failureAttempts = reminder.pendingReminders().getFailureAttempts() + 1;
+        Instant remindAt = Instant.now().plusSeconds(60);
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:155]: isnt there a `plusMinutes(1)`?

Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:155]: just `nanos`, `milis` and `seconds`

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 23 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:146]: ok will update this

Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:146]: image
is this better now?

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 16 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java]: should i hold onto this one for now ? taz mentioned to pass on pendingReminder itself so

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 23 above)
Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:146]: not sure why u want to put it into `(...)`, reads weird imo. the apostrophe should be `Its´` afaik, missing space before the `(` and missing dot at the end of the sentence.

all in all, id go for

> Reminder id 13, content is: hello world please remind me about foo bar blablabla haha

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 16 above)
Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java]: if its possible to use `pendingReminder` itself, then i would prefer that and delete your `Reminder` record

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 23 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:146]: wow been using Its wrong all along, turns out It's and Its are two different things with a slight variations. Apparently It's short for `It is` or `It has`

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 24 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:155]: so should i do this instead? i didn't know it was for mins

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 19 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:62]: for the record, just passed `pendingReminder` and it works

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 23 above)
Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:146]: yeah. and if the apostrophe is put at the end, its means that u possess something, as in "that thing belongs to me".

in any case, those shortcuts generally should not be used in code. intellij also has a warning for it actually

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 24 above)
Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:155]: oops, i meant to have 1 **minute** of delay

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java [hunk 25]
```diff
@@ -137,30 +139,29 @@ static ReminderRoute toPrivate(PrivateChannel channel) {
...
+            .setId(pendingReminder.getId())
+            .setCreatedAt(Instant.from(pendingReminder.getCreatedAt()))
+            .setGuildId(pendingReminder.getGuildId())
+            .setChannelId(pendingReminder.getChannelId())
+            .setAuthorId(pendingReminder.getAuthorId())
             .setRemindAt(remindAt)
-            .setContent(reminder.pendingReminders().getContent())
+            .setContent(pendingReminder.getContent())
             .setFailureAttempts(failureAttempts)
             .insert());
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:166]: Could you try the following instead:

```java
pendingReminder.setRemindAt(remindAt);
pendingReminder.setFailureAttempts(failureAttempts);
pendingReminder.insert();
```

maybe that works as well, then you could get rid of everything else here

**Review by Zabuzard — CHANGES_REQUESTED** [review]

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 25 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:166]: that should work and definitely would clean up the code, ill look into it.

Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java]: updated as requested and pushed the local repo

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java [hunk 26]
```diff
@@ -154,15 +154,13 @@ Failed to send a reminder with (authorID '{}') skipping it. This can be due to a
...
-            .setAuthorId(pendingReminder.getAuthorId())
-            .setRemindAt(remindAt)
-            .setContent(pendingReminder.getContent())
-            .setFailureAttempts(failureAttempts)
-            .insert());
+        database.write(context -> {
+            pendingReminder.setRemindAt(remindAt);
+            pendingReminder.setFailureAttempts(failureAttempts);
+            pendingReminder.insert();
+        });
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:161]: to signal that you dont use `context`, you can call it `any` instead of `context` (in other languages people also like to use `_`, but thats not possible in java)

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java [hunk 27]
```diff
@@ -154,15 +154,13 @@ Failed to send a reminder with (authorID '{}') skipping it. This can be due to a
...
+
+
+
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:164]: 3 newlines seem a bit too much :P

**Review by Zabuzard — CHANGES_REQUESTED** [review]

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 27 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:164]: that's not spotless?

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 26 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:161]: Is it just an FYI or a suggestion to be added?

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 27 above)
Comment (Taz03) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:164]: no

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 26 above)
Comment (Taz03) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:161]: that is a suggestion to be added, when i read the name any, ik that it is not used inside. So u should always have good naming

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 27 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:164]: i don't understand, it's a pre-commit hook and it did what it was supposed to do `format the code` and i thought maybe its Spotless's doing.

Comment (Taz03) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:164]: spotless isn't supposed to format ur code 100%, u can always use some edge case exploit, so thats y the review process is there, just remove the empty lines

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java [hunk 28]
```diff
@@ -142,4 +138,27 @@ static ReminderRoute toPrivate(PrivateChannel channel) {
...
+                        but also happen if the bot disconnected from the target guild and the \
+                        user has disabled DMs or has been deleted. It's reminderId '{}' content includes '{}'.""",
+                        pendingReminder.getAuthorId(), pendingReminder.getContent(),
+                        pendingReminder.getId(), failure);
+            return;
+
+        }
+
+        int failureAttempts = pendingReminder.getFailureAttempts() + 1;
+        Instant remindAt = Instant.now().plus(1, ChronoUnit.MINUTES);
```
Comment (Taz03) [inline application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:156]: y not set it to 1 min after the initial reminding time?

**Review by Taz03 — CHANGES_REQUESTED** [review]

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 28 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:156]: Not sure, followed what zabu suggested.

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 27 above)
Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java]: spotless didnt add those newlines, that must have been u. spotless isnt perfect, it cant remove the newlines unfortunately.

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java [hunk 29]
```diff
@@ -57,7 +57,7 @@ public Schedule createSchedule() {
     @Override
     public void runRoutine(JDA jda) {
         Instant now = Instant.now();
-        database.write(context -> context.selectFrom(PENDING_REMINDERS)
+        database.write(any -> any.selectFrom(PENDING_REMINDERS)
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:60]: this was a mistake. `any` is supposed to indicate **i dont care what or who this parameter is, since i never use it**. but here, you are using it.

**Review by Zabuzard — CHANGES_REQUESTED** [review]

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 28 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:156]: i had a feeling that since `.queue()` was used on each api call then it could be delayed a bit as well

File: application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java (hunk 29 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:60]: but does it matter? isn't it supposed to be just a parameter being passed into the the function? be it `context` or `any`?

Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:60]: but the reader needs to understand what it is, if u are using it. it is the database-context.

i mean, its clear that its important to have a good variable naming. `dogs` instead of `foos` or `objects`. but when you do not actually use it, and the parameter is just forced upon you - but you are not interested, then its idiomatic to call it `any` (or in other languages `_`).

for example, if you have a `List<Pair<String, Int>> persons` int kotlin and want to print all the strings, then u would write `persons.forEach { (name, _) -> println(name) }`. See how it is important to clearly name what the left parameter is, since we didnt use a well named class `Person` but `Pair` instead. But we dont care what the second thing is (`age`), so naming it would only distract the reader. Thats kinda the idea.

Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:60]: from what i can understand, think it's safe to  conclude if im gonna use something, i should care about the name of variable. Thanks for the explanation.

Comment (Taz03) [reply application/src/main/java/org/togetherjava/tjbot/features/reminder/RemindRoutine.java:60]: "when i read any, i know that it is never used inside"

**Review by Taz03 — APPROVED** [review]
