### PR TITLE
Auto-prune of full helper roles

### LINKED ISSUE #483: Auto-prune helpers
## Problem

This is somewhat urgent. Due to a technical limitation, our helper-role system breaks once a helper role has more than 100 users (usually the JAVA helper role).

It fails silently, probably an issue on Discord-end, not on ours. Anyways, we need to mitigate this problem until a proper solution has been found.

## Solution

A way to do this is to automatically prune users from the role who have not posted messages for some time.

For a good UX, we should also attempt to DM the user in order to inform them what has happened. Such as

> You seem to have been inactive for X, hence we removed you from the Y helper role. If that was a mistake, just head back to #active_questions and select the role again. Sorry for any inconvenience caused by this.

Also, this should only activate for roles that are actually approaching the 100-limit (so maybe as soon as they go beyond 90). So maybe create a `Routine` that runs every hour, checking the member count of all helper roles (get via `Config`), and if beyond 90, start pruning it.

### PR DESCRIPTION
**Pull request by Zabuzard**
## Overview

Closes #483. This is a somewhat urgent mitigation due to a technical limitation. Our helper-role system breaks once a helper role has more than 100 users (usually the JAVA helper role).

This mitigates the problem by automatically removing some users from helper roles.

## Details

Roles are pruned once they go beyond `95` users (the hard limit is `100`). It will then attempt to prune `10` **random** users who fulfill:
* not recently joined (**7 days**)
* no recent message in a help thread (**90 days** - this is also the lookback limit of our DB as of today)

Users are send a DM to inform them about what happened:

DM

The routine also logs on `INFO` level who got pruned, so we can always double check in the logs. It will also tell us on `WARN` level if a role is, despite auto-pruning, approaching or even going beyond the limit. So that we can start to prune manually.

Latter warnings are also forwarded to the `#mod_audit_log` channel, so that we really do not miss it:

audit log

## Other stuff

This PR also addresses two unrelated things:

* Added hints on how to change the logging level (also for bot only) in `log4j2.xml`
* Fixed a bug with routines starting too early (they must only be started once the system is ready, not directly during startup)
* Fixed a bug where `BotCore#onReady` is not always triggered because the core is added too late to JDA

### CODE REVIEW

File: application/src/main/java/org/togetherjava/tjbot/commands/help/AutoPruneHelperRoutine.java [hunk 1]
```diff
@@ -0,0 +1,168 @@
...
+        jda.getGuildCache().forEach(this::pruneForGuild);
+    }
+
+    private void pruneForGuild(@NotNull Guild guild) {
+        TextChannel overviewChannel = guild.getTextChannels()
+            .stream()
+            .filter(channel -> helper.isOverviewChannelName(channel.getName()))
+            .findAny()
+            .orElseThrow();
+        Instant when = Instant.now();
```
Comment (marko-radosavljevic) [inline application/src/main/java/org/togetherjava/tjbot/commands/help/AutoPruneHelperRoutine.java:77]:
```suggestion

        Instant now = Instant.now();
```
I think `now` reads better in this context, with usages:

```java

if (Duration.between(memberJoined, when).toDays() <= RECENTLY_JOINED_DAYS)
```
and

```java
Instant latestActiveMoment = when.minus(INACTIVE_AFTER);
```
Your choice, I'm just nitpicking.

**Review by marko-radosavljevic — DISMISSED** [review]
Clean. :relaxed:

File: application/src/main/java/org/togetherjava/tjbot/commands/help/AutoPruneHelperRoutine.java (hunk 1 above)
Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/commands/help/AutoPruneHelperRoutine.java:77]: agreed

File: application/src/main/java/org/togetherjava/tjbot/commands/help/AutoPruneHelperRoutine.java [hunk 2]
```diff
@@ -0,0 +1,168 @@
...
+            @NotNull Instant when) {
+        role.getGuild().findMembersWithRoles(role).onSuccess(members -> {
+            if (isRoleFull(members)) {
+                logger.debug("Helper role {} is full, starting to prune.", role.getName());
+                pruneRole(role, members, overviewChannel, when);
+            }
+        });
+    }
+
+    private boolean isRoleFull(@NotNull Collection<Member> members) {
```
Comment (Tais993) [inline application/src/main/java/org/togetherjava/tjbot/commands/help/AutoPruneHelperRoutine.java:96]: Why not `? extends`

File: application/src/main/java/org/togetherjava/tjbot/commands/help/AutoPruneHelperRoutine.java [hunk 3]
```diff
@@ -0,0 +1,168 @@
...
+        return members.size() >= ROLE_FULL_THRESHOLD;
+    }
+
+    private void pruneRole(@NotNull Role role, @NotNull List<? extends Member> members,
+            @NotNull TextChannel overviewChannel, @NotNull Instant when) {
+        List<Member> membersShuffled = new ArrayList<>(members);
+        Collections.shuffle(membersShuffled);
```
Comment (Tais993) [inline application/src/main/java/org/togetherjava/tjbot/commands/help/AutoPruneHelperRoutine.java:103]: Why the shuffle?

Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/commands/help/AutoPruneHelperRoutine.java:103]: Because we decide to kick out, lets say 10 users out of 30 users eligible for the prune. I dont want this to happen alphabetically or anything, to not put anyone at a disadvantage.

So i am picking the people to prune at random

File: application/src/main/java/org/togetherjava/tjbot/commands/help/AutoPruneHelperRoutine.java (hunk 2 above)
Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/commands/help/AutoPruneHelperRoutine.java:96]: good catch
