### PR TITLE
TopHelpersCommand message is too long

### LINKED ISSUE #603: TopHelpersCommand message is too long
## Issue

The `TopHelpersCommand` message is too long and crashes:

crash

Stacktrace:

stacktrace

Gotta make it a bit smaller.

## Fix

We can just reduce the amount of people it lists from `20` to, lets say, `18`:

https://github.com/Together-Java/TJ-Bot/blob/develop/application/src/main/java/org/togetherjava/tjbot/commands/tophelper/TopHelpersCommand.java#L43

To reproduce the issue locally and test whether that did the trick, one would have to fake the result returned by the DB call here:

https://github.com/Together-Java/TJ-Bot/blob/develop/application/src/main/java/org/togetherjava/tjbot/commands/tophelper/TopHelpersCommand.java#L71

Or directly put some fake data into the database in order to hit the limit of 20 people. Also, they should have a message count of around `10000` each. All of this contributes to the size of the message.

### PR DESCRIPTION
**Pull request by Zabuzard**
## Overview

Fixes #603 which describes a bug when using `/top-helpers` resulting in a too long message, not accepted by Discord.

The approach is simple yet effective:
* reduced the rows from 20 to 18
* abbreviate long user names (limit 15)
* move the description out of the column

these factors effectively reduced the message that was too long from 2300 characters down to 1100 characters, which is perfectively within limits.

## Notes

Since this class also needed abbreviation logic, I elevated the `abbreviate` method from within the `DiscordLogForwarder` to `MessageUtils`. And also gave it a unit test.

### CODE REVIEW

File: application/src/main/java/org/togetherjava/tjbot/commands/tophelper/TopHelpersCommand.java [hunk 1]
```diff
@@ -143,29 +146,30 @@ private static void handleTopHelpers(Collection<TopHelperResult> topHelpers,
                     userIdToMember.get(topHelper.authorId())))
             .toList();
 
-        String message =
-                "```java%n%s%n```".formatted(dataTableToString(topHelpersDataTable, timeRange));
+        String message = """
+                ```java
+                // for %s
```
Comment (Tais993) [inline application/src/main/java/org/togetherjava/tjbot/commands/tophelper/TopHelpersCommand.java:151]: What does this mean, I need some pictures to understand the context

**Review by Tais993 — COMMENTED** [review]
Can you add screenshots of how it looks now?

File: application/src/main/java/org/togetherjava/tjbot/commands/tophelper/TopHelpersCommand.java (hunk 1 above)
Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/commands/tophelper/TopHelpersCommand.java:151]: https://i.imgur.com/bl8MbIP.png

Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/commands/tophelper/TopHelpersCommand.java:151]: And some users with very long names, lets say an user named `FooBarBazHelloWorld` would now be abbreviated to `FooBarBazHel...` (we have the ID on the left anyways)

**Review by Tais993 — APPROVED** [review]
next time give screenshot of before your changes and after.
Would make it a little easier to understand what actually changed

**Comment by Zabuzard** [comment]
> next time give screenshot of before your changes and after. Would make it a little easier to understand what actually changed

sure. was just a bit difficult, since i dont have 20+ users on my private server to make the problem obvious. and i was too lazy to mock the DB just for screenshots.

and the real tables from PROD contained sensitive info that i also was too lazy to mock lol.

but yeah, agreed.

**Review by Taz03 — APPROVED** [review]

**Comment by Zabuzard** [comment]
just rebased, no code changes. already had 2 approvals. merging once pipeline succeeds
