### PR TITLE
Bugfix/role back message

### LINKED ISSUE #946: get role back message is wrong
when you are inactive for a while you get your helper role removerd. he then says to go to #⁠questions to get it again, but you need to go to #⁠select-your-roles. The text needs to be changed.

### PR DESCRIPTION
**Pull request by ankitsmt211**
* adds channel pattern for `select-your-role` in `config.java` and `template`
* method to fetch `select-your-role` channel
* replace `help-forum` with `select-your-channel`
resolves #946 

## Release Note

Changes Config, adds:

```json
"selectRolesChannelPattern": "select-your-roles"
```

### CODE REVIEW

File: application/src/main/java/org/togetherjava/tjbot/features/help/AutoPruneHelperRoutine.java [hunk 1]
```diff
@@ -150,15 +150,16 @@ private boolean isMemberInactive(Member member, Instant when) {
                     .and(HELP_CHANNEL_MESSAGES.SENT_AT.greaterThan(latestActiveMoment)))) == 0;
     }
 
-    private void pruneMemberFromRole(Member member, Role role, ForumChannel helpForum) {
+    private void pruneMemberFromRole(Member member, Role role, JDA jda) {
         Guild guild = member.getGuild();
+        TextChannel selectRolesChannel = getSelectRolesChannel(jda);
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/help/AutoPruneHelperRoutine.java:155]: ur executing this on each member who u prune, instead of finding the channel beforehand **once** and passing the channel down

File: application/src/main/java/org/togetherjava/tjbot/features/help/AutoPruneHelperRoutine.java [hunk 2]
```diff
@@ -173,4 +174,14 @@ private void warnModsAbout(String message, Guild guild) {
...
     }
+
+    private TextChannel getSelectRolesChannel(JDA jda) {
+        Optional<TextChannel> selectRolesChannelOptional = jda.getTextChannels()
+            .stream()
+            .filter(textChannel -> selectYourRolesChannelNamePredicate.test(textChannel.getName()))
+            .findFirst();
+
+        return selectRolesChannelOptional.orElseThrow(() -> new IllegalStateException(
+                "Could not find role selection channel during AutoPruneHelper routine. Make sure the config is setup properly."));
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/help/AutoPruneHelperRoutine.java:185]: the channel isnt necessary for the feature to work. pruning is also more of a background thing, it shouldnt throw exceptions for a missing channel.

have it a warn-log instead and fallback to leaving out the channel part of the DM

**Review by Zabuzard — CHANGES_REQUESTED** [review]

File: application/src/main/java/org/togetherjava/tjbot/features/help/AutoPruneHelperRoutine.java (hunk 1 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/help/AutoPruneHelperRoutine.java:155]: Im not sure if i understand, do you suggest to have a field which use `getRoleSelectChannel` method to get the channel and using that?

Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/help/AutoPruneHelperRoutine.java:155]: i think i understand, you mean instead of passing down jda i should get the channel at the top and pass that instead.

Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/help/AutoPruneHelperRoutine.java:155]: > i think i understand, you mean instead of passing down jda i should get the channel at the top and pass that instead.
yes

**Review by Zabuzard — DISMISSED** [review]

**Comment by ankitsmt211** [comment]
added a minor fix for earlier merge, somehow i managed to sneak  an if block without curlies.

**Review by Zabuzard — APPROVED** [review]
