### PR TITLE
fixed bot positing advice on closed uncategorized help threads

### LINKED ISSUE #571: Bot sends advice on closed uncategorized help threads
Bot sends advice on uncategorized help threads, even after the thread gets closed. This makes it open again

image

### PR DESCRIPTION
**Pull request by Taz03**
fixes #571 

Currently the bot sends a advice to select a category on help threads with no category.

### CODE REVIEW

File: application/src/main/java/org/togetherjava/tjbot/commands/help/HelpSystemHelper.java [hunk 1]
```diff
@@ -274,6 +274,10 @@ private void executeUncategorizedAdviceCheck(long threadChannelId, long authorId
                 return new CompletedRestAction<>(jda, null);
             }
 
+            if (threadChannel.isArchived()) {
+                return null;
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/commands/help/HelpSystemHelper.java:278]: `return null` is the wrong action. this leads to the action crashing with an exception in JDA. instead, do it exactly like the `if` right before this one, with an already-completed action.

**Review by Zabuzard — CHANGES_REQUESTED** [review]

File: application/src/main/java/org/togetherjava/tjbot/commands/help/HelpSystemHelper.java (hunk 1 above)
Comment (Taz03) [reply application/src/main/java/org/togetherjava/tjbot/commands/help/HelpSystemHelper.java:278]: yes, i wanted to ask this. Why i need to return something at all?? when the method returns void shouldn't it be just `return;`??

Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/commands/help/HelpSystemHelper.java]: ur not returning in the method. ur returning in the lambda thats used for the `flatMap` thats expecting a `RestAction<Message>`.

File: application/src/main/java/org/togetherjava/tjbot/commands/help/HelpSystemHelper.java [hunk 2]
```diff
@@ -274,6 +274,10 @@ private void executeUncategorizedAdviceCheck(long threadChannelId, long authorId
                 return new CompletedRestAction<>(jda, null);
             }
 
+            if (threadChannel.isArchived()) {
+                return new CompletedRestAction<>(jda, null);
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/commands/help/HelpSystemHelper.java:278]: please add a debug-level log, similar to the one above. otherwise its hard for us to debug.

**Review by Zabuzard — CHANGES_REQUESTED** [review]

File: application/src/main/java/org/togetherjava/tjbot/commands/help/HelpSystemHelper.java (hunk 1 above)
Comment (Taz03) [reply application/src/main/java/org/togetherjava/tjbot/commands/help/HelpSystemHelper.java]: ohh yea i see, thanks

**Review by Zabuzard — APPROVED** [review]

**Review by Mom0aut — APPROVED** [review]
