### PR TITLE
Bugfix ScamBlocker fails on DM

### LINKED ISSUE #747: ScamBlocker DM failure shouldnt result in an error
The `ScamBlocker` sends DMs to the authors of a message to inform them about the action. Thats totally fine and expected, but failure to DM a user (for example if they blocked DMs), it should not yield to an exception being thrown in the logs:

> ```java
> net.dv8tion.jda.api.requests.RestAction
> ERROR
> RestAction queue returned failure: [ErrorResponseException] 50007: Cannot send messages to this user
> net.dv8tion.jda.api.exceptions.ContextException
> at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
> at net.dv8tion.jda.internal.requests.restaction.operator.RestActionOperator.contextWrap(RestActionOperator.java:123)
> at net.dv8tion.jda.internal.requests.restaction.operator.FlatMapRestAction.queue(FlatMapRestAction.java:50)
> at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:572)
> at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:538)
> at org.togetherjava.tjbot.commands.moderation.scam.ScamBlocker.dmUser(ScamBlocker.java:256)
> at org.togetherjava.tjbot.commands.moderation.scam.ScamBlocker.dmUser(ScamBlocker.java:252)
> at org.togetherjava.tjbot.commands.moderation.scam.ScamBlocker.takeActionAutoDeleteAndQuarantine(ScamBlocker.java:189)
> at org.togetherjava.tjbot.commands.moderation.scam.ScamBlocker.takeAction(ScamBl...
> 01/03/2023 5:52 PM
> ```

The actual DM sending should probably use `mapToResults()` and then maybe send a DEBUG level log message:

code

### PR DESCRIPTION
**Pull request by AthithyaIthayan**
Fixes and closes #747 where the ScamBlocker would crash if attempting to DM an user who blocked DMs.

It will now instead write a DEBUG log message and otherwise ignore the issue.

### CODE REVIEW

File: application/src/main/java/org/togetherjava/tjbot/features/moderation/scam/ScamBlocker.java [hunk 1]
```diff
@@ -251,7 +251,8 @@ private void dmUser(MessageReceivedEvent event) {
     }
 
     private void dmUser(Guild guild, long userId, JDA jda) {
-        jda.openPrivateChannelById(userId).flatMap(channel -> dmUser(guild, channel)).queue();
+        jda.openPrivateChannelById(userId).flatMap(channel -> dmUser(guild, channel)).queue(any -> {
+        }, failure -> logger.debug("failure in Scam blocker Dm  \nTo user id ->" + userId));
```
Comment (Taz03) [inline application/src/main/java/org/togetherjava/tjbot/features/moderation/scam/ScamBlocker.java:255]:
```suggestion
        }, failure -> logger.debug("Unable to send dm message to user {} in guild {}", userId, guild.getId()));
```

better commit my suggestion this time, or else...

**Review by Taz03 — CHANGES_REQUESTED** [review]

File: application/src/main/java/org/togetherjava/tjbot/features/moderation/scam/ScamBlocker.java (hunk 1 above)
Comment (AthithyaIthayan) [reply application/src/main/java/org/togetherjava/tjbot/features/moderation/scam/ScamBlocker.java]: did it

Comment (Taz03) [reply application/src/main/java/org/togetherjava/tjbot/features/moderation/scam/ScamBlocker.java]: noooooooooooo

**Review by Taz03 — APPROVED** [review]

File: application/src/main/java/org/togetherjava/tjbot/features/moderation/scam/ScamBlocker.java [hunk 2]
```diff
@@ -251,7 +251,9 @@ private void dmUser(MessageReceivedEvent event) {
     }
 
     private void dmUser(Guild guild, long userId, JDA jda) {
-        jda.openPrivateChannelById(userId).flatMap(channel -> dmUser(guild, channel)).queue();
+        jda.openPrivateChannelById(userId).flatMap(channel -> dmUser(guild, channel)).queue(any -> {
+        }, failure -> logger.debug("Unable to send dm message to user {} in guild {}", userId,
+                guild.getId()));
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/moderation/scam/ScamBlocker.java:256]: dont silently ignore the actual failure - append it to the logger as last argument `logger.debug(..., failure)`. also, add some context to the message `Unable to send DM to user {} in guild {} to inform them about a scam message being blocked`

**Review by Zabuzard — CHANGES_REQUESTED** [review]

File: application/src/main/java/org/togetherjava/tjbot/features/moderation/scam/ScamBlocker.java (hunk 2 above)
Comment (AthithyaIthayan) [reply application/src/main/java/org/togetherjava/tjbot/features/moderation/scam/ScamBlocker.java]: Sure

**Review by Taz03 — APPROVED** [review]

**Review by Zabuzard — APPROVED** [review]
