### PR TITLE
fix: Handle empty message content for suggestion threads

### LINKED ISSUE #1198: Server suggestion setup fails for a message without text
**Describe the bug**
The bot automatically sets up the up/down votes and a thread to discuss a suggestion.
It fails to do so if someone creates a new post in `#server-suggestions` without text.
For example: https://discord.com/channels/272761734820003841/480829495486447627/1305554470364643442

**Expected behavior**
It shouldn't fail, even for posts without text.

**To Reproduce**
1. Post a new message without text. (only an image for example)
2. See the error

**Additional context**
```
One of the EventListeners had an uncaught exception java.lang.IllegalArgumentException: Name may not be empty
  at net.dv8tion.jda.internal.utils.Checks.notEmpty(Checks.java:94)
  at net.dv8tion.jda.internal.entities.channel.mixin.attribute.IThreadContainerMixin.createThreadChannel(IThreadContainerMixin.java:69)
  at net.dv8tion.jda.internal.entities.ReceivedMessage.createThreadChannel(ReceivedMessage.java:946)
  at org.togetherjava.tjbot.features.basic.SuggestionsUpDownVoter.createThread(SuggestionsUpDownVoter.java:70)
  at org.togetherjava.tjbot.features.basic.SuggestionsUpDownVoter.onMessageReceived(SuggestionsUpDownVoter.java:52)
  at org.togetherjava.tjbot.features.system.BotCore.lambda$onMessageReceived$9(BotCore.java:221)
  at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
  at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
  at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.jav...
```

The bot tries to create a new thread and set the title of that thread using the text of the post:
```java
private static void createThread(Message message) {
    String title = message.getContentRaw();

    if (title.length() >= TITLE_MAX_LENGTH) {
        int lastWordEnd = title.lastIndexOf(' ', TITLE_MAX_LENGTH);

        if (lastWordEnd == -1) {
            lastWordEnd = TITLE_MAX_LENGTH;
        }

        title = title.substring(0, lastWordEnd);
    }

    message.createThreadChannel(title).queue();
}
```

It is missing checks if the text is empty.
What kind of default title would make sense?

### PR DESCRIPTION
**Pull request by billpapat**
Ensures a fallback thread title is provided when the original message content is empty. The thread title will now **default** to the message **author's nickname** in such cases, **preventing empty** or uninformative **thread titles**. Closes #1198

image

### CODE REVIEW

File: application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java [hunk 1]
```diff
@@ -55,19 +55,26 @@ public void onMessageReceived(MessageReceivedEvent event) {
     }
 
     private static void createThread(Message message) {
-        String title = message.getContentRaw();
 
-        if (title.length() >= TITLE_MAX_LENGTH) {
-            int lastWordEnd = title.lastIndexOf(' ', TITLE_MAX_LENGTH);
+        String threadTitle;
+        String messageContent = message.getContentRaw();
```
Comment (christolis) [inline application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java]: References should have an immutable over a mutable state wherever possible and appropriate.

```suggestion
        final String threadTitle;
        final String messageContent = message.getContentRaw();
```

File: application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java [hunk 2]
```diff
@@ -55,19 +55,26 @@ public void onMessageReceived(MessageReceivedEvent event) {
...
             if (lastWordEnd == -1) {
                 lastWordEnd = TITLE_MAX_LENGTH;
             }
 
-            title = title.substring(0, lastWordEnd);
+            threadTitle = messageContent.substring(0, lastWordEnd);
+        } else {
+
+            threadTitle = messageContent;
         }
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java]: could u reorder the if-else slightly so that the big logic block is the last? makes it a bit easier to read imo. so
```java
if (messageContent.isEmpty()) {
  ...
} else if (messageContent.length() < TITLE_MAX_LENGTH) {
  ...
} else {
  ...
}
```

if you got some time i would even find it better to move this into a helper method. then u can also utilize early-return.

```java
private static String createThreadTitle(Message message) {
  String content = ...
  
  if (content.isEmpty()) {
    return ...
  }
  if (content.length() < ...) {
    return content;
  }
  
  ...
  return ...
}
```

File: application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java [hunk 3]
```diff
@@ -55,19 +55,26 @@ public void onMessageReceived(MessageReceivedEvent event) {
...
     private static void createThread(Message message) {
-        String title = message.getContentRaw();
 
-        if (title.length() >= TITLE_MAX_LENGTH) {
-            int lastWordEnd = title.lastIndexOf(' ', TITLE_MAX_LENGTH);
+        String threadTitle;
+        String messageContent = message.getContentRaw();
+
+        if (messageContent.isEmpty()) {
+            threadTitle = message.getAuthor().getName();
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java]: Can we go for not just the name but something more human readable. E.g. "Suggestion by John" or "Johns suggestion".

**Review by christolis — CHANGES_REQUESTED** [review]
+ what @Zabuzard suggested. We should prioritize code readability.

**Review by Zabuzard — CHANGES_REQUESTED** [review]

File: application/src/main/java/org/togetherjava/tjbot/features/basic/ThreadTitle.java [hunk 4]
```diff
@@ -0,0 +1,38 @@
+
+package org.togetherjava.tjbot.features.basic;
+
+public record ThreadTitle(String value) {
```
Comment (christolis) [inline application/src/main/java/org/togetherjava/tjbot/features/basic/ThreadTitle.java]: There should be JavaDocs for this record.

File: application/src/main/java/org/togetherjava/tjbot/features/basic/ThreadTitle.java [hunk 5]
```diff
@@ -0,0 +1,38 @@
...
+
+            threadTitle = value.substring(0, lastWordEnd);
+        } else {
+            threadTitle = value;
+        }
+
+        this.value = threadTitle;
+    }
+
+    public static ThreadTitle withFallback(String threadtitle, String fallback) {
```
Comment (christolis) [inline application/src/main/java/org/togetherjava/tjbot/features/basic/ThreadTitle.java]: Can name something like `threadtitle` as `primary`, and regardless, rename the original one to `threadTitle`.

File: application/src/main/java/org/togetherjava/tjbot/features/basic/ThreadTitle.java (hunk 4 above)
Comment (billpapat) [reply application/src/main/java/org/togetherjava/tjbot/features/basic/ThreadTitle.java]: Done!

File: application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java (hunk 1 above)
Comment (billpapat) [reply application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java]: Done!

File: application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java (hunk 3 above)
Comment (billpapat) [reply application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java]: Done!

File: application/src/main/java/org/togetherjava/tjbot/features/basic/ThreadTitle.java (hunk 5 above)
Comment (billpapat) [reply application/src/main/java/org/togetherjava/tjbot/features/basic/ThreadTitle.java]: Done!

File: application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java (hunk 2 above)
Comment (billpapat) [reply application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java]: Done!

File: application/src/main/java/org/togetherjava/tjbot/features/basic/ThreadTitle.java (hunk 4 above)
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/basic/ThreadTitle.java]: Mh. This class is too specific for the Suggestions-Voter feature to be put into its own class right into the `features/basic` package.

Either create a subpackage for the whole suggestions voting topic or move this back into the old class as `private record` 👍

Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/basic/ThreadTitle.java]: Im not sure if its worth making this a `record`. You are only using it in this one single spot. I think it might be better to just have this as simple `private static String createTitle(...)` method in your previous class and then utilize early-return to have the logic clean and readable without all that nesting :)

File: application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java [hunk 6]
```diff
@@ -55,26 +54,10 @@ public void onMessageReceived(MessageReceivedEvent event) {
     }
 
     private static void createThread(Message message) {
+        ThreadTitle threadTitle = ThreadTitle.withFallback(message.getContentRaw(),
+                message.getAuthor().getName() + "'s suggestions");
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java]: Singular I would say, `suggestion`

**Review by Zabuzard — CHANGES_REQUESTED** [review]

File: application/src/main/java/org/togetherjava/tjbot/features/basic/ThreadTitle.java (hunk 4 above)
Comment (billpapat) [reply application/src/main/java/org/togetherjava/tjbot/features/basic/ThreadTitle.java]: Done

File: application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java [hunk 7]
```diff
@@ -23,9 +23,9 @@
  */
 public final class SuggestionsUpDownVoter extends MessageReceiverAdapter {
     private static final Logger logger = LoggerFactory.getLogger(SuggestionsUpDownVoter.class);
-    private static final int TITLE_MAX_LENGTH = 60;
     private static final Emoji FALLBACK_UP_VOTE = Emoji.fromUnicode("👍");
     private static final Emoji FALLBACK_DOWN_VOTE = Emoji.fromUnicode("👎");
+    private static final int THREAD_TITLE_MAX_LENGTH = 60; // Define the max length
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java]: that comment feels unecessary. id remove it

File: application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java [hunk 8]
```diff
@@ -55,19 +55,35 @@ public void onMessageReceived(MessageReceivedEvent event) {
...
+        message.createThreadChannel(threadTitle).queue();
+    }
 
-        if (title.length() >= TITLE_MAX_LENGTH) {
-            int lastWordEnd = title.lastIndexOf(' ', TITLE_MAX_LENGTH);
+    /**
+     * Generates a thread title, enforcing a maximum length of 60 characters. If an initial title
+     * exceeds this limit, it's truncated at the last word boundary before or at the 60-character
+     * mark to prevent cutting words mid-sentence. If no space is found, it truncates at 60
+     * characters. Uses a fallback title if the primary title is empty.
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java]: If you write `60` here, this documentation will quickly get outdated when someone adjusts the constant but forgets to also adjust it down here.
You can link the value instead in the Javadoc: `maximum length of {@value #THREAD_TITLE_MAX_LENGTH}`. something like that, you can check it if you mousehover.

Imo the responsibilities for this method would be better if you give it the thread and it figures out how to build the title from that. I.e. imo the method should take `generateThreadTitle(Message message)` and extract title and fallback by itself.

I.e. a method named `generateThreadTitle` should be the one responsible for figuring out the proper title.

Further, I personally find this javadoc too implementation-specific. Perhaps just:

> Generates a title for the given message.

How it then does that is up to the method and imo the code is readable enough to understand it without being put into plain english sentences again 👍

**Review by Zabuzard — CHANGES_REQUESTED** [review]

File: application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java [hunk 9]
```diff
@@ -55,19 +55,33 @@ public void onMessageReceived(MessageReceivedEvent event) {
...
+    /**
+     * Generates a title for the given message. The maximum length of the title is
+     * {@value #THREAD_TITLE_MAX_LENGTH}.
+     *
+     * @param message The message for which to generate the title.
+     * @return The generated and truncated thread title.
+     */
+    private static String generateThreadTitle(Message message) {
+        String primaryTitle = message.getContentRaw();
+        String fallbackTitle = message.getAuthor().getName() + "'s suggestion";
```
Comment (Taz03) [inline application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java]: this will use their username rather than nickname, i think using their nickname is a better option

File: application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java [hunk 10]
```diff
@@ -55,19 +55,33 @@ public void onMessageReceived(MessageReceivedEvent event) {
...
+        String title = primaryTitle.isEmpty() ? fallbackTitle : primaryTitle;
```
Comment (Taz03) [inline application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java:72]: trim it before checking for isEmpty

File: application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java [hunk 11]
```diff
@@ -55,19 +55,33 @@ public void onMessageReceived(MessageReceivedEvent event) {
...
 
-            if (lastWordEnd == -1) {
-                lastWordEnd = TITLE_MAX_LENGTH;
-            }
+        if (title.length() < THREAD_TITLE_MAX_LENGTH) {
```
Comment (Taz03) [inline application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java]: less than or equal to

File: application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java [hunk 12]
```diff
@@ -55,19 +55,33 @@ public void onMessageReceived(MessageReceivedEvent event) {
...
-            int lastWordEnd = title.lastIndexOf(' ', TITLE_MAX_LENGTH);
+    /**
+     * Generates a title for the given message. The maximum length of the title is
+     * {@value #THREAD_TITLE_MAX_LENGTH}.
+     *
+     * @param message The message for which to generate the title.
+     * @return The generated and truncated thread title.
+     */
+    private static String generateThreadTitle(Message message) {
+        String primaryTitle = message.getContentRaw();
```
Comment (Taz03) [inline application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java]: use [Message#getContentStripped](https://javadoc.io/doc/net.dv8tion/JDA/latest/net/dv8tion/jda/api/entities/Message.html#getContentStripped()) instead

File: application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java (hunk 11 above)
Comment (Taz03) [inline application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java]: i think this branch is kinda useless?? not sure, if its not pls just close this conversation

**Review by Taz03 — CHANGES_REQUESTED** [review]

File: application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java (hunk 9 above)
Comment (billpapat) [reply application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java]: Done!

File: application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java (hunk 10 above)
Comment (billpapat) [reply application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java:72]: Done!

File: application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java (hunk 11 above)
Comment (billpapat) [reply application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java]: Done!

Comment (billpapat) [reply application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java]: It is needed to return the title as it is (<= THREAD_TITLE_MAX_LENGTH).

**Review by Zabuzard — CHANGES_REQUESTED** [review]
could u add some screenshots to the PR please that showcase/demo the feature in practice? its always difficult to review these things when u cant see how it actually looks in practice. often one also spots improvement opportunities that way :)

File: application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java (hunk 10 above)
Comment (Taz03) [reply application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java:72]: you are still not calling trim
```java
String primaryTitle = message.getContentStripped().trim();
```

Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/basic/SuggestionsUpDownVoter.java:72]: note that there is `isBlank()`. prefer that over `.trim().isEmpty()`

**Review by Zabuzard — APPROVED** [review]

**Review by Taz03 — APPROVED** [review]
