### PR TITLE
handle threads when authorId found

### LINKED ISSUE #1067: HelpThreadAutoArchiver can't find author from database
# About

Since the new release, this error comes up a lot of times. 
Might be worth looking into.

stacktrace

### PR DESCRIPTION
**Pull request by ankitsmt211**
Resolves #1067 
Error:
when retrieving threads from DB, helper method would try to get active thread channel and match it's ID with thread record from DB. If a match happens, it would then grab authorID from that record and go on with rest of archive flow (retrieve user and then chooses to archive thread with or without mentioning author based on results)

Changes:
* Dividing archive logic into two parts, if a record match happens in DB aka authorId is found or not
    * `triggerArchiveFlow`
    * `triggerAuthorIdNotFoundArchiveFlow`

### CODE REVIEW

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadAutoArchiver.java [hunk 1]
```diff
@@ -151,4 +156,11 @@ private void handleArchiveFlow(ThreadChannel threadChannel, MessageEmbed embed)
             .flatMap(any -> threadChannel.getManager().setArchived(true))
             .queue();
     }
+
+    private void triggerAuthorIdNotFoundArchiveFlow(ThreadChannel threadChannel,
```
Comment (Taz03) [inline application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadAutoArchiver.java:160]: maybe also log the thread channel id

**Review by Taz03 — APPROVED** [review]

**Review by SquidXTV — APPROVED** [review]
