### PR TITLE
BugFix: Bot mentions itself in Help-Thread at Timeout

### LINKED ISSUE #968: Bot pings itself when auto-archiving thread due to inactivity
**Describe the bug**

When a help thread is inactive for more than 12 hrs, it's auto archived by a routine. During auto-archive it pings OP and sends some information about why the thread was closed. Ideally it would ping OP, but with `transfer-feature` help threads also contains Embed posted on behalf of OP by TJ-Bot. In that case, to auto-archive routine it seems as if author of post is Bot itself and hence the ping to itself.

**Expected behavior**
It should ping the effective author of post(if post contains an embed than find author of embed, otherwise just the author of thread is fine).

**To Reproduce**

1. Transfer a message using `apps>transfer-feature` from message context menu.
2. Wait for 12 hrs of inactivity for routine to trigger(if working on local machine, can change duration of inactivity from 12 hrs to a couple minutes and change that for routine time interval as well).

**Screenshots**
image

**Additional context**
Auto-archive(`HelpThreadAutoArchiver.java`) routine is inside `features/help` package. 
if owner of thread is bot, get the embed from message that started this thread. 
Then get the owner of that embed, that is the effective author of post and should be used to ping.

`HelpThreadAutoArchiver.java:133` ->
`.retrieveMemberById(threadChannel.getOwnerIdLong())//retrives owner of thread`
 `.flatMap(author -> threadChannel.sendMessage(author.getAsMention()).addEmbeds(embed))//pings that owner`

### PR DESCRIPTION
**Pull request by firasrg**
resolves #968 
Comments:
* HelpSystemHelper: new method to retrieve help-thread data from db;
* HelpThreadCreatedListener:
  * new method to extract unique user from bot first msg in help-thread;
  * add author control on help-thread creation;

### CODE REVIEW

**Comment by ankitsmt211** [comment]
Could you add screenshots of ping in action on auto-archive please?

**Comment by firasrg** [comment]
Hi @ankitsmt211 and thanks for your attention 😀

This is a animated demo
demo-1

**Review by Taz03 — CHANGES_REQUESTED** [review]
remove the @NotNulls (see package-info)

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java [hunk 1]
```diff
@@ -81,7 +79,17 @@ private boolean wasThreadAlreadyHandled(long threadChannelId) {
...
 
     private void handleHelpThreadCreated(ThreadChannel threadChannel) {
-        helper.writeHelpThreadToDatabase(threadChannel.getOwnerIdLong(), threadChannel);
+        threadChannel.retrieveMessageById(threadChannel.getIdLong()).queue(message -> {
+
+            long idAuthor = threadChannel.getOwnerIdLong();
+
+            if (isPostedByBot(message)) {
+                idAuthor = getAuthorFromPostByBot(message).getIdLong(); // check if bot otherwise
+                                                                        // returns author ID
```
Comment (ankitsmt211) [inline application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:88]: i think you may have misunderstood my intent of putting comments in earlier review here , they were just meant to sort of brief what method will do. Since now the method is pretty clear about the intent, we can safely drop these `//check if bot otherwise return author ID` comments.

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java [hunk 2]
```diff
@@ -81,7 +78,16 @@ private boolean wasThreadAlreadyHandled(long threadChannelId) {
     }
 
     private void handleHelpThreadCreated(ThreadChannel threadChannel) {
-        helper.writeHelpThreadToDatabase(threadChannel.getOwnerIdLong(), threadChannel);
+        threadChannel.retrieveMessageById(threadChannel.getIdLong()).queue(message -> {
+
+            long idAuthor = threadChannel.getOwnerIdLong();
```
Comment (Taz03) [inline application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:83]: `authorId` makes more sense

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java [hunk 3]
```diff
@@ -90,6 +96,28 @@ private void handleHelpThreadCreated(ThreadChannel threadChannel) {
...
+        if (users.size() != 1) {
+
+            String errorMsg = "Attempts to open a help-thread for multiple authors.";
+
+            if (users.isEmpty()) {
+                errorMsg = "Attempts to open a help-thread without any author.";
+            }
+
+            throw new IllegalStateException(errorMsg);
+        }
```
Comment (Taz03) [inline application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:112]: there are many things wrong here
1. nested if statement is never reachable
2. the error message "Attempts to open...." doesn't make sense the bot is trying to close it
3. in the current state of the bot the number of pings can never exceed 1

so just check if its not 1, and throw the error, the error message should be along the lines of "Cannot find original user in help-thread: <ID>"

Comment (Taz03) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:112]: ohh ig ur right, i misread the code

> I don't see a technical guarantee for that

wdym? the bot will in no  case  ping more than 1 person

Comment (firasrg) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:112]: I know but what to do in case of sudden error or a misbehavior (like mentioning a wrong user or a role)? Ig throwing an exception is helpful 🤷‍♂️

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java [hunk 4]
```diff
@@ -81,15 +79,64 @@ private boolean wasThreadAlreadyHandled(long threadChannelId) {
...
+        // and must have only one user
+
+        if (users.isEmpty()) {
+            throw new IllegalStateException("Attempts to open a help-thread without any author.");
+        }
+
+        if (users.size() > 1) {
+            throw new IllegalStateException(
+                    "Attempts to open a help-thread for more than one author.");
+        }
```
[the remark this answers is not in the document]
Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java]: the empty check is also unecessary. let it naturally throw an exception when u access the first element.

[the remark this answers is not in the document]
Comment (firasrg) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java]: I thought employing control over the list to ensure a single user is mentioned is a prudent approach, especially when the scenario anticipates that. But okay, i'm going to remove.

**Comment by firasrg** [comment]
@ankitsmt211 I've made a new update, please take a look.

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadAutoArchiver.java [hunk 5]
```diff
@@ -129,8 +131,14 @@ private void handleArchiveFlow(ThreadChannel threadChannel, MessageEmbed embed)
             }
         };
 
+        logger.debug("Attempt to fetch thread-record from db, with ID: {} ", threadChannel.getId());
```
Comment (ankitsmt211) [inline application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadAutoArchiver.java:134]: was there a specific reason for extra unit of space? although it doesn't matter but to be consistent throughout.
```suggestion
        logger.debug("Attempt to fetch thread-record from db, with ID: {}", threadChannel.getId());
```

Comment (firasrg) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadAutoArchiver.java:134]: No, consider it as a typo

**Review by ankitsmt211 — APPROVED** [review]
Seems solid, great work 👍
Welcome to the project🎉

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadAutoArchiver.java (hunk 5 above)
Comment (firasrg) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadAutoArchiver.java]: @ankitsmt211 i just noticed something thanks to what you said here, I think this _logger.debug()_ is unnecessary. As there is already a similar log inside  `helper.getThreadRecordByChannelId()`. So may be it's better to delete it 🤔

Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadAutoArchiver.java]: Yep that seems reduntant, ideally it should reside in method handling db stuff only. I think you're good to remove it.

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java [hunk 6]
```diff
@@ -355,4 +357,39 @@ public String getTagName() {
...
+            return database.read(ctx -> ctx.selectFrom(HELP_THREADS)
+                .where(HELP_THREADS.CHANNEL_ID.eq(channelID))
+                .limit(1)
+                .fetchOptional());
+
+        } catch (DataAccessException ex) {
+
+            logger
+                .error("Something went wrong while trying to fetch data from thread-record table");
+
```
Comment (ankitsmt211) [inline application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java:391]: Do we need log level ERROR here? maybe warn or lower since we're already handling it.

Comment (firasrg) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java:391]: Hmm, well if it's **handled**, maybe the whole `try..catch` is unnecessary 🤔

Comment (firasrg) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java]: @ankitsmt211 i've changed it into a warning.

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java [hunk 7]
```diff
@@ -355,4 +357,36 @@ public String getTagName() {
...
+            return database.read(ctx -> ctx.selectFrom(HELP_THREADS)
+                .where(HELP_THREADS.CHANNEL_ID.eq(channelID))
+                .limit(1)
+                .fetchOptional());
+
+        } catch (DataAccessException ex) {
+            logger.warn("Something went wrong while trying to fetch data from thread-record table");
+            return Optional.empty();
+        }
```
Comment (Taz03) [inline application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java:390]: as i can see in other places in the codebase, database reads aren't in try catch
```suggestion
            return database.read(ctx -> ctx.selectFrom(HELP_THREADS)
                .where(HELP_THREADS.CHANNEL_ID.eq(channelID))
                .limit(1)
                .fetchOptional());
```

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java [hunk 8]
```diff
@@ -355,4 +357,36 @@ public String getTagName() {
...
+     * @throws DataAccessException if something is wrong with database
+     *
+     */
+    Optional<HelpThreadsRecord> getThreadRecordByChannelId(final long channelID) {
+
+        logger.debug("Looking for thread-record using channel ID: {}", channelID);
+
+        try {
+
+            return database.read(ctx -> ctx.selectFrom(HELP_THREADS)
```
Comment (Taz03) [inline application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java:382]: don't abbreviate
```suggestion
            return database.read(context -> context.selectFrom(HELP_THREADS)
```

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadAutoArchiver.java [hunk 9]
```diff
@@ -129,8 +131,12 @@ private void handleArchiveFlow(ThreadChannel threadChannel, MessageEmbed embed)
             }
         };
 
+        HelpThreadsRecord threadRecord =
+                helper.getThreadRecordByChannelId(threadChannel.getIdLong())
+                    .orElseThrow(() -> new NoSuchElementException("No help-thread with such ID"));
```
Comment (Taz03) [inline application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadAutoArchiver.java:136]: mention the id as well

**Review by Taz03 — CHANGES_REQUESTED** [review]

**Review by Taz03 — CHANGES_REQUESTED** [review]

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java (hunk 6 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java]: if we drop the try-catch, the exception `NoSuchElement` exception should be thrown when method is called right?

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java (hunk 7 above)
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java:390]: optional should not be used to indicate error.
let the exception naturally happen, dont catch it.

also, ur javadoc says that the exception happens (for an outside user) in case of issue - but thats not true right now, as u caught and swallowed it. just remove the try-catch-log thing entirely and then adjust ur doc

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java (hunk 6 above)
Comment (firasrg) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java]: Sure. That exception means that no element has been found in database. Im going to remove the `try..catch` block.

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java [hunk 10]
```diff
@@ -355,4 +357,36 @@ public String getTagName() {
...
+     *
+     * @param channelID is channel unique identifier
+     *
+     * @return An Optional containing the HelpThreadsRecord for the specified channel ID, or an
+     *         empty Optional if no matching record is found.
+     *
+     * @throws DataAccessException if something is wrong with database
+     *
+     */
+    Optional<HelpThreadsRecord> getThreadRecordByChannelId(final long channelID) {
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java:376]: the helper method is useful, but even more useful would be to offer `getOpByHelpThreadId`. then the 3 other places that also suffer from the same problem could use the helper method as well.

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadAutoArchiver.java (hunk 9 above)
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadAutoArchiver.java:136]: useless extra behavior. just `orElseThrow()` would essentially do the same, with less clutter.

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java (hunk 10 above)
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java:376]: u should not return a `...Record` class, as that keeps the database connection alive. that class must not be persisted by anyone or used for longer than necessary. just create the actual helper method u need, namely `getOpByHelpThreadId` instead. Then u also dont need to query the DB for all data of the row, but only the data u actually need (author)

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java [hunk 11]
```diff
@@ -2,10 +2,7 @@
 
 import com.github.benmanes.caffeine.cache.Cache;
 import com.github.benmanes.caffeine.cache.Caffeine;
-import net.dv8tion.jda.api.entities.Member;
-import net.dv8tion.jda.api.entities.Message;
-import net.dv8tion.jda.api.entities.MessageEmbed;
-import net.dv8tion.jda.api.entities.Role;
+import net.dv8tion.jda.api.entities.*;
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:5]: adjust ur IDE rules, no star imports.

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java [hunk 12]
```diff
@@ -81,7 +78,16 @@ private boolean wasThreadAlreadyHandled(long threadChannelId) {
     }
 
     private void handleHelpThreadCreated(ThreadChannel threadChannel) {
-        helper.writeHelpThreadToDatabase(threadChannel.getOwnerIdLong(), threadChannel);
+        threadChannel.retrieveMessageById(threadChannel.getIdLong()).queue(message -> {
+
+            long authorId = threadChannel.getOwnerIdLong();
+
+            if (isPostedByBot(message)) {
+                authorId = message.getMentions().getUsers().get(0).getIdLong();
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:86]: not obvious what this code does if ur not familiar with the feature. needs a comment or a helper method instead

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java [hunk 13]
```diff
@@ -90,6 +96,10 @@ private void handleHelpThreadCreated(ThreadChannel threadChannel) {
             .queueAfter(5, TimeUnit.SECONDS);
     }
 
+    private static boolean isPostedByBot(Message message) {
+        return message.getAuthor().isBot();
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:100]: that also triggers for other bots. instead, use self-user. sth like `message.getAuthor().isSelfUser()` (lookup JDA docs for details)

**Review by Zabuzard — CHANGES_REQUESTED** [review]

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java (hunk 7 above)
Comment (firasrg) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java:390]: im gonna put this in a commit

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java (hunk 10 above)
Comment (firasrg) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java:376]: I don't get what you mean here. You want me to create a new method `getOpByHelpThreadId()` or rename `getThreadRecordByChannelId()` ?

> then the 3 other places that also suffer from the same problem could use the helper method as well.

You want me to look around for these 3 places ?

Comment (firasrg) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java:376]: > Then u also dont need to query the DB for all data of the row, but only the data u actually need (author)

Sorry I don't get this, would you like to give more explanation please 🤔

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java (hunk 11 above)
Comment (firasrg) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:5]: I'm using the _GoogleStyle_ config, right from the project under _./meta/formatting_ directory i think it auto sets the settings for all code styles including _imports_ 🤔

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java (hunk 13 above)
Comment (firasrg) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:100]: Would you like to provide a link to help me out, because i didn't find any `isSelfUser()` by googling.

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java (hunk 10 above)
Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java:376]: you created a helper method, but not the actual helper method that is needed.
what you need is a method that gives you the real author of a help thread, thats the helper method we need. also, because multiple other classes have this mistake as well, they need it as well.

instead of `getThreadRecordByChannelId`, create `getHelpThreadAuthor(long channelId)`.

Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java:376]: `HelpThreadsRecord` is a class that must not be kept alive for longer than a few milliseconds. it holds the connection to the database open, as it has methods like `record.update()` or `record.delete()` which then feed back straight into the database.

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java (hunk 13 above)
Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:100]: `jda.getSelfUser()`

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java (hunk 10 above)
Comment (firasrg) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java:376]: > because multiple other classes have this mistake as well, they need it as well.

Good note, but I'd not touch any other classes to keep this PR modular. The updates for other classes can be done later in another issue.

Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java:376]: ye, it's out of scope for this one. Those can be handled later.

**Comment by firasrg** [comment]
Hello @Zabuzard @ankitsmt211 and @Taz03 i've made a new update, please take a look, I think it's well settled this time 🫡

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadAutoArchiver.java [hunk 14]
```diff
@@ -27,8 +27,8 @@
  */
 public final class HelpThreadAutoArchiver implements Routine {
     private static final Logger logger = LoggerFactory.getLogger(HelpThreadAutoArchiver.class);
-    private static final int SCHEDULE_MINUTES = 60;
-    private static final Duration ARCHIVE_AFTER_INACTIVITY_OF = Duration.ofHours(12);
+    private static final int SCHEDULE_MINUTES = 15;
```
Comment (firasrg) [inline application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadAutoArchiver.java:30]: Oh no! i fogot these _DEV only_ changes, let me fix them up 🤦‍♂️🤦‍♂️

**Review by Taz03 — DISMISSED** [review]

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java [hunk 15]
```diff
@@ -355,4 +355,15 @@ public String getTagName() {
...
+
+    long getOpByHelpThreadId(final long channelId) {
+
+        logger.info("Looking for thread-record using channel ID: {}", channelId);
+
+        return database.read(context -> context.selectFrom(HelpThreads.HELP_THREADS)
+            .where(HelpThreads.HELP_THREADS.CHANNEL_ID.eq(channelId))
+            .fetchOptional()
+            .orElseThrow()
+            .getAuthorId());
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java:367]: 1. instead of fetching the entire row and then picking the only column ur interested in, directly only select that column: `select(author id).from(help threads)...`
2. it is not safe to assume that the method always finds a result - even in normal situations. for example if the bot was down for a few minutes and hours and threads have been created in the meantime. the bot is supposed to be able to naturally handly this situation, so u must not throw an exception here. instead go for returning `OptionalLong`.
3. id rename it to `getAuthor...` instead of `getOp...` for consistency with the rest of the code.

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java [hunk 16]
```diff
@@ -50,8 +50,9 @@ public final class HelpThreadCreatedListener extends ListenerAdapter
      *
      * @param helper to work with the help threads
      */
-    public HelpThreadCreatedListener(HelpSystemHelper helper) {
+    public HelpThreadCreatedListener(HelpSystemHelper helper, JDA jda) {
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:53]: its unecessary for u to memorize JDA, as u can get hands on the JDA instance on pretty much any jda class already.
i.e. in ur code below, just do `threadChannel.getJda()` and u have it

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java [hunk 17]
```diff
@@ -90,6 +100,14 @@ private void handleHelpThreadCreated(ThreadChannel threadChannel) {
             .queueAfter(5, TimeUnit.SECONDS);
     }
 
+    private static User getMentionedAuthorByMessage(Message message) {
+        return message.getMentions().getUsers().get(0);
+    }
+
+    private boolean isPostedByBot() {
+        return jda.getSelfUser().isBot();
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:108]: that code is incorrect and always true. ur testing whether the self-user (i.e. the bot) is a bot - thats always true.

instead, u want to test whether the user who posted the message is the self user.

**Review by Zabuzard — CHANGES_REQUESTED** [review]

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java (hunk 17 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:108]: @Zabuzard  Im not sure if i understand this part, "self-user" is supposed to be logged in account? we're checking if the message that started thread is posted by Bot, if not then we can rely on `threadChannel.getOwnerIdLong()`.

Comment (firasrg) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:108]: @Zabuzard i tried to find a method in the Message object like `message.getSelfUser()` and it doesn't exist, there is only `isBot()`. You told me previously to use JDA's `getSelfUser()` for this situation. tbh I feel confused now 😵

Comment (Zabuzard) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:108]: @ankitsmt211  self-user is the logged in user, yes. i.e. tj-bot. we are not trying to check if the message was posted by _a bot_ (there are multiple bots), but that it was posted by tj-bot (self user).

@firasrg i said `threadChannel.getJda().getSelfUser()` and then `message.getAuthor().equals(selfUser)` (or compare their IDs)

**Comment by firasrg** [comment]
@Zabuzard I've made a new update, please take a look 👀

**Comment by ankitsmt211** [comment]
@firasrg please resolve conflicts.

**Comment by firasrg** [comment]
@ankitsmt211 I've just fixed the conflict, please take a look.

**Comment by firasrg** [comment]
I see that something is wrong in build, im checking @ankitsmt211

**Comment by firasrg** [comment]
@ankitsmt211 i have a weired issue here. The log told me `Run './gradlew :application:spotlessApply' to fix these violations.`. i run it on whole project, and got no changes ?!

**Comment by ankitsmt211** [comment]
> @ankitsmt211 i have a weired issue here. The log told me `Run './gradlew :application:spotlessApply' to fix these violations.`. i run it on whole project, and got no changes ?!

are you sure? it should format your code to match the project standards that's all, if changes are made you can do check em via `git status`

**Comment by firasrg** [comment]
@ankitsmt211 I've made changes, ig now it's fine. I've squashed my review commits into one, it's better.

**Comment by firasrg** [comment]
Sorry i tried to rename this branch as the name is not significant. but np

**Review by ankitsmt211 — DISMISSED** [review]
Everything looks solid 👍
Thanks 😊
on a sidenote: Commits are already squashed on merge.

**Review by Taz03 — DISMISSED** [review]

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java [hunk 18]
```diff
@@ -355,4 +355,14 @@ public String getTagName() {
             return tagName;
         }
     }
+
+    Optional<Long> getAuthorByHelpThreadId(final long channelId) {
+
+        logger.info("Looking for thread-record using channel ID: {}", channelId);
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java:361]: too spammy. please use debug or trace

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadAutoArchiver.java [hunk 19]
```diff
@@ -133,20 +133,17 @@ private void handleArchiveFlow(ThreadChannel threadChannel, MessageEmbed embed)
...
-                        "Owner of thread with id: {} left the server, sending embed without mention",
-                        threadChannel.getId(), foundMember.getFailure());
-
-                return sendEmbedWithoutMention.get();
-            })
-            .flatMap(any -> threadChannel.getManager().setArchived(true))
-            .queue();
+        long authorId = helper.getAuthorByHelpThreadId(threadChannel.getIdLong()).orElseThrow();
+
+        threadChannel.getGuild().retrieveMemberById(authorId).mapToResult().flatMap(foundMember -> {
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadAutoArchiver.java:138]: odd naming, `foundMember` sounds like `boolean`, but its not. its also unclear which member ur looking for.
better would be `authorResults`

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadAutoArchiver.java [hunk 20]
```diff
@@ -133,20 +133,17 @@ private void handleArchiveFlow(ThreadChannel threadChannel, MessageEmbed embed)
...
+            if (foundMember.isSuccess()) {
+                return sendEmbedWithMention.apply(foundMember);
+            }
+            logger.info(
+                    "Owner of thread with id: {} left the server, sending embed without mention",
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadAutoArchiver.java:143]: missing context. should say what it attempted to do, i.e. archiving a thread.

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java [hunk 21]
```diff
@@ -90,6 +97,14 @@ private void handleHelpThreadCreated(ThreadChannel threadChannel) {
             .queueAfter(5, TimeUnit.SECONDS);
     }
 
+    private static User getMentionedAuthorByMessage(Message message) {
+        return message.getMentions().getUsers().get(0);
+    }
+
+    private boolean isPostedByBot(ThreadChannel channel, Message message) {
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:104]: confusing name. name implies it would check for any bot, but it actually only checks for self user. rename to `isPostedBySelfUser`

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java [hunk 22]
```diff
@@ -81,7 +79,16 @@ private boolean wasThreadAlreadyHandled(long threadChannelId) {
...
 
     private void handleHelpThreadCreated(ThreadChannel threadChannel) {
-        helper.writeHelpThreadToDatabase(threadChannel.getOwnerIdLong(), threadChannel);
+        threadChannel.retrieveMessageById(threadChannel.getIdLong()).queue(message -> {
+
+            long authorId = threadChannel.getOwnerIdLong();
+
+            if (isPostedByBot(threadChannel, message)) {
+                authorId = getMentionedAuthorByMessage(message).getIdLong();
+            }
```
Comment (Zabuzard) [inline application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java:88]: it would be helpful to add a comment like `// transfer-command used`

**Review by Zabuzard — CHANGES_REQUESTED** [review]

File: application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadAutoArchiver.java (hunk 19 above)
Comment (ankitsmt211) [reply application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadAutoArchiver.java:138]: This is from a PR from that was merged recently, but you're right it does sound like boolean. But the goal was to make it clear what it holds or not. Because it can or cannot have a member we're looking for.

**Review by Taz03 — APPROVED** [review]
